# Aljabar Matriks


#Penjelasan Mengenai Matriks
##Pengertian Matriks:
Matriks adalah susunan bilagan real(atau elemen-elemen) yang disusun dalam baris dan kolom sehingga membentuk persegi ataupun persegi panjang. Setiap elemen memiliki posisi unik dalam matriks, ditentukan oleh baris dan kolomnya. Misalnya, matriks 2x3 memiliki 2 baris dan 3 kolom. suatu matriks biasa diberi nama dengan menggunakan huruf kapital (seperti A, B dll) dan elemennya dinyatakan dengan huruf kecil.


### Berikut Contoh Matriks
\begin{align*}
A=
\begin{bmatrix}
2&3&2\\
4&1&-3\\
-1&-2&2
\end{bmatrix}
&&
B=
\begin{bmatrix}
2&4&7\\
6&-3&2\\
5&-2&7
\end{bmatrix}
&&
C=
\begin{bmatrix}
3&4\\
-2&4\\
2&5
\end{bmatrix}
\end{align*}


#Operasi pada Matriks
Operasi matriks adalah serangkaian operasi atau tindakan yang dilakukan pada matriks, baik itu untuk mengubah matriks ataupun menggabungkan matriks. Berikut beberapa operasi matriks yang sering digunakan:

In [ ]:
import numpy as np

a=np.array([[2,3,2],[4,1,-3],[-1,-2,2]])
b=np.array([[2,4,7],[6,-3,2],[5,-2,7]])
c=np.array([[3,4],[-2,4],[2,5]])

print('A=\n',a)
print('B=\n',b)
print('C=\n',c)

A=
 [[ 2  3  2]
 [ 4  1 -3]
 [-1 -2  2]]
B=
 [[ 2  4  7]
 [ 6 -3  2]
 [ 5 -2  7]]
C=
 [[ 3  4]
 [-2  4]
 [ 2  5]]


PENJELASAN :

1. - import numpy as np

      - Penjelasan : memanggil library numpy yang kemudian di simpan dalam variable np

2. - np.array

      - Penjelasan : digunakan untuk membuat matriks dengan cepat dan efisien

##1.Penjumlahan matriks :

Operasi ini melibatkan penambahan elemen-elemen yang berada pada posisi yang sama dari dua matriks yang memiliki ordo yang sama. Artinya kedua matriks ini harus memiliki baris dan kolom yang sama.

CONTOH PENJUMLAHAN MATRIKS A + B :
\begin{align*}
A=
\begin{bmatrix}
2&3&2\\
4&1&-3\\
-1&-2&2
\end{bmatrix}
&&
B=
\begin{bmatrix}
2&4&7\\
6&-3&2\\
5&-2&7
\end{bmatrix}
\end{align*}

\begin{align*}
A + B =
\begin{bmatrix}
2+2&3+4&2+7\\
4+6&1+(-3)&-3+2\\
-1+5&-2+(-2)&2+7
\end{bmatrix}
=
\begin{bmatrix}
4&7&9\\
10&-2&-1\\
4&-4&9
\end{bmatrix}
\end{align*}

BERIKUT CODE PENJUMLAHAN MATRIKS DENGAN MENGGUNAKAN ATAU MEMANGGIL LIBRARY NUMPY:



In [ ]:
import numpy as np

a=np.array([[2,3,2],[4,1,-3],[-1,-2,2]])
b=np.array([[2,4,7],[6,-3,2],[5,-2,7]])

print('A+B=\n',a+b)
print('B+A=\n',b+a)
print('Sifat di atas merupakan sifat komutatif karena A+B = B+A')

A+B=
 [[ 4  7  9]
 [10 -2 -1]
 [ 4 -4  9]]
B+A=
 [[ 4  7  9]
 [10 -2 -1]
 [ 4 -4  9]]
Sifat di atas merupakan sifat komutatif karena A+B = B+A


##2.Pengurangan Matriks:

Operasi ini melibatkan pengurangan elemen-elemen yang berada pada posisi yang sama dari dua matriks yang memiliki ordo yang sama. Artinya kedua matriks ini harus memiliki baris dan kolom yang sama.

CONTOH PENGURANGAN MATRIKS:

\begin{align*}
A=
\begin{bmatrix}
2&3&2\\
4&1&-3\\
-1&-2&2
\end{bmatrix}
&&
B=
\begin{bmatrix}
2&4&7\\
6&-3&2\\
5&-2&7
\end{bmatrix}
\end{align*}

\begin{align*}
A - B =
\begin{bmatrix}
2-2&3-4&2-7\\
4-6&1-(-3)&-3-2\\
-1-5&-2-(-2)&2-7
\end{bmatrix}
=
\begin{bmatrix}
0&-1&-5\\
-2&4&-5\\
-6&-0&-5
\end{bmatrix}
\end{align*}

BERIKUT CODE PERKALIAN MATRIKS DENGAN MENGGUNAKAN ATAU MEMANGGIL LIBRARY NUMPY:

In [ ]:
import numpy as np

a=np.array([[2,3,2],[4,1,-3],[-1,-2,2]])
b=np.array([[2,4,7],[6,-3,2],[5,-2,7]])

print('A-B=\n',a-b)
print('B-A=\n',b-a)
print('Sifat di BUKAN merupakan sifat komutatif karena A-B TIDAK SAMA DENGAN B-A')

A-B=
 [[ 0 -1 -5]
 [-2  4 -5]
 [-6  0 -5]]
B-A=
 [[ 0  1  5]
 [ 2 -4  5]
 [ 6  0  5]]
Sifat di BUKAN merupakan sifat komutatif karena A-B TIDAK SAMA DENGAN B-A


##3.Perkalian Matriks:

Operasi ini melibatkan perkalian elemen-elemen matriks. Untuk melakukan perkalian matriks A dan B, jumlah kolom dalam matriks A harus sama dengan jumlah baris dalam matriks B. Contoh matriks A memiliki ordo atau ukuran mxn, maka matriks B harus memiliki ordo atau ukuran nxp. Sehingga hasil dari perkalian tersebut akan menghasilkan matriks baru dengan ukuran mxp. Hasilnya akan memiliki jumlah baris yang sama dengan matriks A dan jumlah kolom yang sama dengan matriks B.

CONTOH PERKALIAN MATRIKS:


\begin{align*}
A=
\begin{bmatrix}
2&3&2\\
4&1&-3\\
-1&-2&2
\end{bmatrix}
&&
B=
\begin{bmatrix}
2&4&7\\
6&-3&2\\
5&-2&7
\end{bmatrix}
\end{align*}

\begin{align*}
A X B =
\begin{bmatrix}
2(2)+3(6)+2(5) &2(4)+3(-3)+2(-2)&2(7)+3(2)+2(7)\\
4(2)+1(6)+(-3)(5) &4(4)+1(-3)+(-3)(-2) &4(7)+1(2)+(-3)(7)\\
-1(2)+(-2)(6)+2(5) &-1(4)+(-2)(-3)+2(-2) &-1(7)+(-2)(2)+2(7)
\end{bmatrix}
\end{align*}

\begin{align*}
AB=
\begin{bmatrix}
32&-5&34\\
-1&19&9\\
-4&-2&3
\end{bmatrix}
\end{align*}

BERIKUT CODE PERKALIAN MATRIKS DENGAN MENGGUNAKAN ATAU MEMANGGIL LIBRARY NUMPY:

In [ ]:
import numpy as np

a=np.array([[2,3,2],[4,1,-3],[-1,-2,2]])
b=np.array([[2,4,7],[6,-3,2],[5,-2,7]])
c=np.array([[3,4],[-2,4],[2,5]])

print('AB=\n',a@b)
print('AC=\n',a@c)
print('BC=\n',b@c)

AB=
 [[32 -5 34]
 [-1 19  9]
 [-4 -2  3]]
AC=
 [[ 4 30]
 [ 4  5]
 [ 5 -2]]
BC=
 [[12 59]
 [28 22]
 [33 47]]


- Sifat Asosiasi:

Dengan sifat asosiasi, urutan dalam melakukan operasi perhitungan tidak mempengaruhi hasil akhir.

  (AB)C = A(BC)

In [ ]:
import numpy as np

a=np.array([[2,3,2],[4,1,-3],[-1,-2,2]])
b=np.array([[2,4,7],[6,-3,2],[5,-2,7]])
c=np.array([[3,4],[-2,4],[2,5]])

print('A(BC) =\n', a@(b@c))
print('(AB)C =\n',(a@b)@c)

A(BC) =
 [[174 278]
 [-23 117]
 [ -2  -9]]
(AB)C =
 [[174 278]
 [-23 117]
 [ -2  -9]]


- Perkalian skalar:

Perkalian skalar adalah operasi yang melibatkan pengalihan suatu vektor oleh bilangan, yang disebut skalar. Biasanya skalar merupakan bilangan riil.

  c(AB) = (cA)B = A(cB)

In [ ]:
import numpy as np

a=np.array([[2,3,2],[4,1,-3],[-1,-2,2]])
b=np.array([[2,4,7],[6,-3,2],[5,-2,7]])
c=np.array([[3,4],[-2,4],[2,5]])

c = 3
print('c(AB)=\n',c*(a@b))
print('(cA)B=\n',(c*a)@b)
print('A(cB)=\n',a@(c*b))

c(AB)=
 [[ 96 -15 102]
 [ -3  57  27]
 [-12  -6   9]]
(cA)B=
 [[ 96 -15 102]
 [ -3  57  27]
 [-12  -6   9]]
A(cB)=
 [[ 96 -15 102]
 [ -3  57  27]
 [-12  -6   9]]


- Perkalian identitas:

Dalam operasi perkalian ini, matriks dikalikan dengan matriks identitas. Dimana matriks identitas merupakan matriks persegi yang memiliki semua elemen di luar diagonal utama bernilai 1, dan elemen di luar diagonal utama bernilai 0. Matriks identitas dilambangkan dengan I. Contoh :

\begin{align*}
I=
\begin{bmatrix}
1&0&0\\
0&1&0\\
0&0&1
\end{bmatrix}
\end{align*}


  AI = IA = A

In [ ]:
import numpy as np

a=np.array([[2,3,2],[4,1,-3],[-1,-2,2]])

i = np.array([[1,0,0],[0,1,0],[0,0,1]])
print('AI=\n',a@i)
print('IA=\n',i@a)
print('A=\n',a)

AI=
 [[ 2  3  2]
 [ 4  1 -3]
 [-1 -2  2]]
IA=
 [[ 2  3  2]
 [ 4  1 -3]
 [-1 -2  2]]
A=
 [[ 2  3  2]
 [ 4  1 -3]
 [-1 -2  2]]


- Tidak berlaku sifat kumutatif:

Karena sifat komutatif membutuhkan bahwa operasi tidak dipengaruhi oleh urutan perkalian. Sementara matriks dipengaruhi oleh urutan perkalian. Sehingga:

  AB != BA atau AB tidak sama dengan BA

In [ ]:
import numpy as np

a=np.array([[2,3,2],[4,1,-3],[-1,-2,2]])
b=np.array([[2,4,7],[6,-3,2],[5,-2,7]])

print('AB=\n',a@b)
print('BA=\n',b@a)

AB=
 [[32 -5 34]
 [-1 19  9]
 [-4 -2  3]]
BA=
 [[13 -4  6]
 [-2 11 25]
 [-5 -1 30]]


##4.Transpose Matriks

Transpose matriks adalah matriks baru yang diperoleh dengan cara menukar elemen-elemen baris menjadi elemen kolom atau sebaliknya. Jika sebuah matriks berukuran M X N, maka transpose matriks tersebut memiliki ordo N X M.

CONTOH TRANSPOSE MATRIKS:

\begin{align*}
C=
\begin{bmatrix}
3&4\\
-2&4\\
2&5
\end{bmatrix}
&&
CT (C Transposre)=
\begin{bmatrix}
3&-2&2\\
4&4&-5
\end{bmatrix}
\end{align*}

BERIKUT CODE UNTUK MENG-TRANSPOSE MATRIKS DENGAN MENGGUNAKAN ATAU MEMANGGIL LIBRARY NUMPY:

In [ ]:
import numpy as np

c=np.array([[3,4],[-2,4],[2,5]])

c_tran = c.transpose()
print('matrik c sebelum di transpose=\n', c)
print('matrik c setelah di transpose=\n',c_tran)
print('ordo C_transpose adalah',c_tran.shape)
z=c_tran@c
print('Z = C_transpose x C =\n',z)
print('ordo z adalah',z.shape)
p=c@c_tran
print('P = C_transpose x C =\n',p)
print('ordo P adalah',p.shape)
print("Dapat disimpulkan bahwa C_transpose X C tidak sama dengan C X C_transpose")

matrik c sebelum di transpose=
 [[ 3  4]
 [-2  4]
 [ 2  5]]
matrik c setelah di transpose=
 [[ 3 -2  2]
 [ 4  4  5]]
ordo C_transpose adalah (2, 3)
Z = C_transpose x C =
 [[17 14]
 [14 57]]
ordo z adalah (2, 2)
P = C_transpose x C =
 [[25 10 26]
 [10 20 16]
 [26 16 29]]
ordo P adalah (3, 3)
Dapat disimpulkan bahwa C_transpose X C tidak sama dengan C X C_transpose


Penjelasan :

- c_tran.shape

    - shape disini berfungsi untuk mengetahui ordo dari matriks c_tran dengan memanggil fungsi di dalam library numpy

#Program untuk Mengalikan Matriks dengan Menggunakan Perulangan (Loop) For :

In [ ]:
def perkalian(matrix1, matrix2):
    if len(matrix1[0]) != len(matrix2):
        print("Perkalian matriks tidak dapat dilakukan karena jumlah kolom dalam matriks pertama tidak sama dengan jumlah baris dalam matriks kedua")
        return None
    result = [[0 for _ in range(len(matrix2[0]))] for _ in range(len(matrix1))]
    for i in range(len(matrix1)):
        for j in range(len(matrix2[0])):
            for k in range(len(matrix2)):
                result[i][j] += matrix1[i][k] * matrix2[k][j]
    return result

def tampilan_hasil(matrix):
    for baris in matrix:
        print(baris)

print ("Berikut adalah contoh matriks")
print ("""
matriks 1=([[2,3,2],[4,1,-3],[-1,-2,2]])
matriks 1=([[2,4,7],[6,-3,2],[5,-2,7]])
""")
matriks1=([[2,3,2],[4,1,-3],[-1,-2,2]])
matriks2=([[2,4,7],[6,-3,2],[5,-2,7]])
test = perkalian(matriks1, matriks2)
print("\nHasil perkalian matriks:")
tampilan_hasil(test)

Berikut adalah contoh matriks

matriks 1=([[2,3,2],[4,1,-3],[-1,-2,2]])
matriks 1=([[2,4,7],[6,-3,2],[5,-2,7]])


Hasil perkalian matriks:
[32, -5, 34]
[-1, 19, 9]
[-4, -2, 3]


BERIKUT PENJELASAN MENGENAI CODINGAN DI ATAS:

1. Fungsi perkalian matriks :
  - def perkalian(matrix1, matrix2):
    
     - Penjelasan : sebuah fungsi bernama 'perkalian' yang memiliki dua parameter yaitu matrix1 dan matrix2.

  - if len(matrix1[0]) != len(matrix2):

        print("Perkalian matriks tidak dapat dilakukan karena jumlah kolom dalam matriks pertama tidak sama dengan jumlah baris dalam matriks kedua")
        
        return None
      - Penjelasan : pengujian awal untuk memastikan bahwa matriks dapat dikalikan. Jika jumlah kolom dalam matrix1 tidak sama dengan jumlah baris dalam matrix2, maka perkalian matriks tidak bisa dilakukan. Dalam hal ini, fungsi akan mencetak pesan kesalahan dan mengembalikan None.

  - result = [[0 for _ in range(len(matrix2[0]))] for _ in range(len(matrix1))]

      - Penjelasan : sebuah matriks kosong yang akan menyimpan hasil perkalian matriks matrix1 dan matrix2. Panjang dan lebar matriks ini akan sama dengan panjang baris dari matrix1 dan panjang kolom dari matrix2.

  - for i in range(len(matrix1)):

      - Penjelasan : akan mengiterasi melalui setiap baris dari matriks 1

  - for j in range(len(matrix2[0])):

      - Penjelasan : akan mengiterasi melalui setiap kolom dari matriks 2

  - for k in range(len(matrix2)):

      - Penjelasan : akan mengiterasi melalui setiap elemen dari baris 'i' pada matriks 1 dan kolom 'j' pada matriks 2

  - result[i][j] += matrix1[i][k] * matrix2[k][j]

      - Penjelasan : nilai result[i][j] akan diakumulasikan (dikumpulkan atau menambah nilai-nilai secara bertahap atau berurutan) dengan hasil perkalian matriks1[i][k] * matriks2[k][j]

  - return result

      - Penjelasan : mengembalikan hasil perkalian matriks yang telah dihhitung.


2. fungsi untuk menampilkan hasil perkalian matriks:

  - def tampilan_hasil(matrix):

      - Penjelasan : sebuah fungsi bernnama 'tampilan_hasil' dengan satu parameter yaitu 'matrix'

  - for baris in matrix:

      - Penjelasan : untuk mengiterasi setiap baris dalam 'matriks'. Setiap iterasi akan mengambil satu baris dari matriks.

  - print (baris)

      - Penjelasan : akan mencetak baris dari matriks

3. - print ("Berikut adalah contoh matriks")

      - Penjelasan : perintah untuk menampilkan 'Berikut adalah contoh matriks'

4. -  print ("""
matriks 1=([[2,3,2],[4,1,-3],[-1,-2,2]])
matriks 1=([[2,4,7],[6,-3,2],[5,-2,7]])
""")

      - Penjelasan : perintah untuk menampilkan 'matriks 1=([[2,3,2],[4,1,-3],[-1,-2,2]])
matriks 1=([[2,4,7],[6,-3,2],[5,-2,7]])'

5. - matriks1=([[2,3,2],[4,1,-3],[-1,-2,2]])

      - Penjelasan : sebuah variable bernama 'matriks1' yang berisikan suatu matriks dengan ordo 3x3 di dalam list

6. - matriks2=([[2,4,7],[6,-3,2],[5,-2,7]])

      - Penjelasan : sebuah variable bernama 'matriks2' yang berisikan suatu matriks dengan ordo 3x3 di dalam list

7. - test = perkalian(matriks1, matriks2)

      - Penjelasan : sebuah variable bernama 'test' yang digunakan untuk memanggil fungsi bernama 'perkalian' dan menyimpan hasil dari fungsi tersebut dengan menggunakan variable 'matriks1' sebagai parameter pertama dan 'matriks2' sebagai parameter kedua

8. - print("\nHasil perkalian matriks:")

      - Penjelasan : perintah untuk menampilkan 'Hasil perkalian matriks:' tanda '\n' untuk membuat baris baru

9. - tampilan_hasil(test)

      - Penjelasan : memanggil fungsi bernama 'tampiilan_hasil' dengan menggunakan variable bernama 'test' untuk menampilkan hasil perkalian matriks



Dengan penjelasan diatas dapat menunjukkan bahwa jika kita menggunakan perulangan untuk melakukan perkalian matriks tidaklah praktis. jadi akan lebih mudah jika kita memanggil (menggunakan) library Numpy. Karena selain lebih sederhana juga mengirit baris pada code dan waktu yang digunakan lebih sedikit.