In [ ]:
import numpy as np

# Fungsi untuk menghitung kofaktor
def cofactor(matrix, i, j):
    minor = np.delete(np.delete(matrix, i, axis=0), j, axis=1)
    cof = (-1) ** (i + j) * np.linalg.det(minor)
    return cof

# Matriks contoh
matrix = np.array([[3, 1, 3],
                   [2, 1, 2],
                   [4, 2, 1]])

# Mendapatkan ukuran matriks
rows, cols = matrix.shape

# Membuat matriks kofaktor
cofactor_matrix = np.zeros((rows, cols))

for i in range(rows):
    for j in range(cols):
        cofactor_matrix[i, j] = cofactor(matrix, i, j)

print("Matriks Kofaktor:")
print(cofactor_matrix)


Matriks Kofaktor:
[[-3.  6.  0.]
 [ 5. -9. -2.]
 [-1. -0.  1.]]


In [ ]:
import numpy as np

# Matriks contoh
matrix = np.array([[3,1,3],
                   [2,1,2],
                   [4,2,1]])

# Menghitung invers matriks
inverse_matrix = np.linalg.inv(matrix)

print("Invers Matriks:")
print(inverse_matrix)


Invers Matriks:
[[ 1.         -1.66666667  0.33333333]
 [-2.          3.         -0.        ]
 [ 0.          0.66666667 -0.33333333]]


In [ ]:
#A invers = adj A / det A

import numpy as np

# Fungsi untuk menghitung kofaktor
def cofactor(matrix, i, j):
    minor = np.delete(np.delete(matrix, i, axis=0), j, axis=1)
    cof = (-1) ** (i + j) * np.linalg.det(minor)
    return cof

# Matriks contoh
matrix = np.array([[3,1],
                   [2, 1]])

# Mendapatkan ukuran matriks
rows, cols = matrix.shape

# Membuat matriks kofaktor
cofactor_matrix = np.zeros((rows, cols))

for i in range(rows):
    for j in range(cols):
        cofactor_matrix[i, j] = cofactor(matrix, i, j)

print("Matriks Kofaktor:")
print(cofactor_matrix)


Matriks Kofaktor:
[[ 1. -2.]
 [-1.  3.]]


In [ ]:
import numpy as np

# Matriks contoh
matrix = np.array([[3,1],
                   [2, 1]])

# Mengitung Determinant
determinant = np.linalg.det(matrix)

print("Determinan Matriks:", determinant.round())

# Menghitung invers matriks
inverse_matrix = np.linalg.inv(matrix)

print("Invers Matriks:")
print(inverse_matrix)

# Menghitung transpose matriks
transpose_matrix = inverse_matrix.T

print("Transpose Matriks(kofaktor):")
print(transpose_matrix)

Determinan Matriks: 1.0
Invers Matriks:
[[ 1. -1.]
 [-2.  3.]]
Transpose Matriks:
[[ 1. -2.]
 [-1.  3.]]


In [ ]:
#menghitung determinan dan invers matriks, kofaktor, matriks 5x5

In [1]:
import numpy as np

matrix_S = np.array([[4,2,1,1,3],[3,2,1,2,2],[4,1,1,1,1],[1,3,4,1,2],[2,2,1,1,3]])
det_Mat_S = np.linalg.det(matrix_S)
inv_Mat_S = np.linalg.inv(matrix_S)
print(f"pembuktian Determinan= {det_Mat_S}")
print(f"pembuktian Invers = \n{inv_Mat_S.round(1)}")
print()
print("="*50)
# kita mencari determinannya terlebih dahulu dengan Pick setiap row

S11 = np.array([[2,1,1,2],[1,1,1,1],[3,4,1,2],[2,1,1,3]])
S12 = np.array([[3,1,2,2],[4,1,1,1],[1,4,1,2],[2,1,1,3]])
S13 = np.array([[3,2,2,2],[4,1,1,1],[1,3,1,2],[2,2,1,3]])
S14 = np.array([[3,2,1,2],[4,1,1,1],[1,3,4,2],[2,2,1,3]])
S15 = np.array([[3,2,1,2],[4,1,1,1],[1,3,4,1],[2,2,1,1]])
S21 = np.array([[2,1,1,3],[1,1,1,1],[3,4,1,2],[2,1,1,3]])
S22 = np.array([[4,1,1,3],[4,1,1,1],[1,4,1,2],[2,1,1,3]])
S23 = np.array([[4,2,1,3],[4,1,1,1],[1,3,1,2],[2,2,1,3]])
S24 = np.array([[4,2,1,3],[4,1,1,1],[1,3,4,2],[2,2,1,3]])
S25 = np.array([[4,2,1,1],[4,1,1,1],[1,3,4,1],[2,2,1,1]])
S31 = np.array([[2,1,1,3],[2,1,2,2],[3,4,1,2],[2,1,1,3]])
S32 = np.array([[4,1,1,3],[3,1,2,2],[1,4,1,2],[2,1,1,3]])
S33 = np.array([[4,2,1,3],[3,2,2,2],[1,3,1,2],[2,2,1,3]])
S34 = np.array([[4,2,1,3],[3,2,1,2],[1,3,4,2],[2,2,1,3]])
S35 = np.array([[4,2,1,1],[3,2,1,2],[1,3,4,1],[2,2,1,1]])
S41 = np.array([[2,1,1,3],[2,1,2,2],[1,1,1,1],[2,1,1,3]])
S42 = np.array([[4,1,1,3],[3,1,2,1],[4,1,1,1],[2,1,1,3]])
S43 = np.array([[4,2,1,3],[3,2,2,2],[4,1,1,1],[2,2,1,3]])
S44 = np.array([[4,2,1,3],[3,2,1,2],[4,1,1,1],[2,2,1,3]])
S45 = np.array([[4,2,1,1],[3,2,1,2],[4,1,1,1],[2,2,1,1]])
S51 = np.array([[2,1,1,3],[2,1,2,2],[1,1,1,1],[3,4,1,2]])
S52 = np.array([[4,1,1,3],[3,1,2,2],[4,1,1,1],[1,4,1,2]])
S53 = np.array([[4,2,1,3],[3,2,2,2],[4,1,1,1],[1,3,1,2]])
S54 = np.array([[4,2,1,3],[3,2,1,2],[4,1,1,1],[1,3,4,2]])
S55 = np.array([[4,2,1,1],[3,2,1,2],[4,1,1,1],[1,3,4,1]])
print(f"Marix11 = \n{S11}")
print()
det_11 = np.linalg.det(S11)
det_12 = np.linalg.det(S12)
det_13 = np.linalg.det(S13)
det_14 = np.linalg.det(S14)
det_15 = np.linalg.det(S15)
det_21 = np.linalg.det(S21)
det_22 = np.linalg.det(S22)
det_23 = np.linalg.det(S23)
det_24 = np.linalg.det(S24)
det_25 = np.linalg.det(S25)
det_31 = np.linalg.det(S31)
det_32 = np.linalg.det(S32)
det_33 = np.linalg.det(S33)
det_34 = np.linalg.det(S34)
det_35 = np.linalg.det(S35)
det_41 = np.linalg.det(S41)
det_42 = np.linalg.det(S42)
det_43 = np.linalg.det(S43)
det_44 = np.linalg.det(S44)
det_45 = np.linalg.det(S45)
det_51 = np.linalg.det(S51)
det_52 = np.linalg.det(S52)
det_53 = np.linalg.det(S53)
det_54 = np.linalg.det(S54)
det_55 = np.linalg.det(S55)

c11 = (-1)**(1+1) * det_11
c12 = (-1)**(1+2) * det_12
c13 = (-1)**(1+3) * det_13
c14 = (-1)**(1+4) * det_14
c15 = (-1)**(1+5) * det_15
c21 = (-1)**(2+1) * det_21
c22 = (-1)**(2+2) * det_22
c23 = (-1)**(2+3) * det_23
c24 = (-1)**(2+4) * det_24
c25 = (-1)**(2+5) * det_25
c31 = (-1)**(3+1) * det_31
c32 = (-1)**(3+2) * det_32
c33 = (-1)**(3+3) * det_33
c34 = (-1)**(3+4) * det_34
c35 = (-1)**(3+5) * det_35
c41 = (-1)**(4+1) * det_41
c42 = (-1)**(4+2) * det_42
c43 = (-1)**(4+3) * det_43
c44 = (-1)**(4+4) * det_44
c45 = (-1)**(4+5) * det_45
c51 = (-1)**(5+1) * det_51
c52 = (-1)**(5+2) * det_52
c53 = (-1)**(5+3) * det_53
c54 = (-1)**(5+4) * det_54
c55 = (-1)**(5+5) * det_55

a11 = matrix_S[0][0]
a12 = matrix_S[0][1]
a13 = matrix_S[0][2]
a14 = matrix_S[0][3]
a15 = matrix_S[0][4]
a21 = matrix_S[1][0]
a22 = matrix_S[1][1]
a23 = matrix_S[1][2]
a24 = matrix_S[1][3]
a25 = matrix_S[1][4]
a31 = matrix_S[2][0]
a32 = matrix_S[2][1]
a33 = matrix_S[2][2]
a34 = matrix_S[2][3]
a35 = matrix_S[2][4]
a41 = matrix_S[3][0]
a42 = matrix_S[3][1]
a43 = matrix_S[3][2]
a44 = matrix_S[3][3]
a45 = matrix_S[3][4]
a51 = matrix_S[4][0]
a52 = matrix_S[4][1]
a53 = matrix_S[4][2]
a54 = matrix_S[4][3]
a55 = matrix_S[4][4]

# Row 1
det_S_row1 = a11*c11 + a12*c12 + a13*c13 + a14*c14 + a15*c15
print(f"det s = {det_S_row1}")
# Row 2
det_S_row2 = a21*c21 + a22*c22 + a23*c23 + a24*c24 + a25*c25
print(f"det s = {det_S_row2}")
# Row 3
det_S_row3 = a31*c31 + a32*c32 + a33*c33 + a34*c34 + a35*c35
print(f"det s = {det_S_row3}")
# Row 4
det_S_row4 = a41*c41 + a42*c42 + a43*c43 + a44*c44 + a45*c45
print(f"det s = {det_S_row4}")
# Row 5
det_S_row5 = a51*c51 + a52*c52 + a53*c53 + a54*c54 + a55*c55
print(f"det s = {det_S_row5}")
print()
Kof_Matrix_S = np.array([[c11,c12,c13,c14,c15],[c21,c22,c23,c24,c25],[c31,c32,c33,c34,c35],[c41,c42,c43,c44,c45],[c51,c52,c53,c54,c55]])
print(f"Marix dengan anggota kofaktor-kofaktornya = \n{Kof_Matrix_S}")
print()
Trans_Kof_Matrix_S = Kof_Matrix_S.transpose()
print(f"Transpose Matrix dari kofaktornya = \n{Trans_Kof_Matrix_S}")
print()
invers_S = 1 / det_S_row1 * Trans_Kof_Matrix_S
print(f"Hasil Invers Matrix adalah = \n{invers_S.round(1)}")

pembuktian Determinan= -5.999999999999996
pembuktian Invers = 
[[ 0.5  0.   0.   0.  -0.5]
 [ 5.7  2.  -4.3  0.7 -6. ]
 [-2.5 -1.   2.  -0.   2.5]
 [-2.8 -0.   1.7 -0.3  2.5]
 [-2.3 -1.   1.7 -0.3  3. ]]

Marix11 = 
[[2 1 1 2]
 [1 1 1 1]
 [3 4 1 2]
 [2 1 1 3]]

det s = -5.999999999999957
det s = -5.999999999999998
det s = -6.000000000000014
det s = -6.0
det s = -6.000000000000028

Marix dengan anggota kofaktor-kofaktornya = 
[[ -3. -34.  15.  17.  14.]
 [ -0. -12.   6.   0.   6.]
 [  0.  26. -12. -10. -10.]
 [ -0.  -4.  -0.   2.   2.]
 [  3.  36. -15. -15. -18.]]

Transpose Matrix dari kofaktornya = 
[[ -3.  -0.   0.  -0.   3.]
 [-34. -12.  26.  -4.  36.]
 [ 15.   6. -12.  -0. -15.]
 [ 17.   0. -10.   2. -15.]
 [ 14.   6. -10.   2. -18.]]

Hasil Invers Matrix adalah = 
[[ 0.5  0.  -0.   0.  -0.5]
 [ 5.7  2.  -4.3  0.7 -6. ]
 [-2.5 -1.   2.   0.   2.5]
 [-2.8 -0.   1.7 -0.3  2.5]
 [-2.3 -1.   1.7 -0.3  3. ]]
