# DETERMINANT

Nilai determinan matriks memberikan informasi tentang apakah matriks tersebut memiliki invers (jika determinannya tidak nol), apakah matriks tersebut singuler atau tidak. Jika determinan suatu matriks adalah nol, maka matriks tersebut disebut sebagai matriks singular, yang artinya tidak memiliki invers. Sedangkan jika determinannya bukan nol, maka matriks tersebut disebut sebagai matriks nonsingular atau invertible, yang artinya memiliki invers.



## Syarat Mencari Determinan Matriks :
Hanya dapat dilakukan pada matriks bujur sangkar atau matriks persegi atau matriks yang mempunyai baris = kolom





## Sifat-sifat Determinan

1. Determinan dari matriks identitas = 1. Atau dapat ditulis det(I)=1
2. jika suatu matriks dikalikan dengan konstanta maka rumus dekterminannya:

    -> constanta^berapa baris atau kolom yang dikalikan dengan konstanta(hasil determinan dari matriks asalnya)

    atau
    
    -> K^n(det(matriks asal))

      keterangan :

      - K = konstanta

      - n = baris atau kolom yang telah dikalikan dengan dengan konstanta

      - det(matriks asal) = determinan dari matriks asal

3. jika matriks segitiga atas atau segitiga bawah dicari determinannya maka akan menghasilkan perkalian dari elemen di diagonalnya
4. $det(AB) = det(A)det(B)$
5. $det(A^-1) =  1/det(A)$
6. $det(A)^2 = det(A).det(A)$
7. $det(A^T) = det(A)$
  - Zero row -> zero column
  - Same row -> same column
8. $det(A+B) != det(A) + det(B)$

In [1]:
import numpy as np

#fungsi mencari determinant
def det(matriks):
    return np.linalg.det(matriks)

print("Membuktikan bahwa determinan dari matriks identitas adalah 1")
I=np.array([[1,0,0],[0,1,0],[0,0,1]])
print('Matriks A =\n', I)
print("determinan dari matriks i adalah",det(I))

print("perubahan baris pada matriks identitas untuk mencari determinannya")
I2=np.array([[1,0,0],[0,0,1],[0,1,0]])
print("determinan dari matriks i setelah diubah pertama kali adalah",det(I2))
I3=np.array([[0,1,0],[0,0,1],[1,0,0]])
print("determinan dari matriks i setelah diubah kedua kali adalah",det(I3),"\n")

print("mencari determinan c")
c = np.array([[1,2,1],[3,1,2],[2,1,2]])
print("determinan dari matriks c adalah",det(c).round())
d = np.array([[3,1,2],[1,2,1],[2,1,2]])
print("determinan dari matriks c setelah diubah pertama kali adalah",det(d).round())
e = np.array([[1,2,1],[2,4,2],[2,1,2]])
print("determinan dari matriks e adalah",det(e).round())
print("jika baris dikalikan dengan kelipatan maka hasilnya akan 0")
f = np.array([[1,2,1],[2,4,2],[2,4,3]])
print("determinan dari matriks f adalah",det(f).round())
g = np.array([[6,2,4],[2,4,2],[4,2,4]])
print("determinan dari matriks g adalah",det(g).round())#2^3(3)-> 2=konstanta, ^3=jumlah baris yang dikalikan dengan konstanta, (3)=hasil dari det(c)
a=np.array([[3,4],[2,1]])
print("determinan dari matriks a adalah",det(a).round())
h=np.array([[6,8],[4,2]])
print("determinan dari matriks h adalah",det(h).round()) #2^2(-5)=-20
i=np.array([[6,8],[2,1]])
print("determinan dari matriks i adalah",det(i).round()) #jika hanya satu baris saja c det(a) = 2(-5) = -10

print("\nmengalikan salah satu kolom ")
j=np.array([[6,4],[4,1]])
print("determinan dari matriks j adalah",det(j).round())#hasilnya bakal sama dengan yang salah satu baris saja yang dikalikan

Membuktikan bahwa determinan dari matriks identitas adalah 1
Matriks A =
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
determinan dari matriks i adalah 1.0
perubahan baris pada matriks identitas untuk mencari determinannya
determinan dari matriks i setelah diubah pertama kali adalah -1.0
determinan dari matriks i setelah diubah kedua kali adalah 1.0 

mencari determinan c
determinan dari matriks c adalah -3.0
determinan dari matriks c setelah diubah pertama kali adalah 3.0
determinan dari matriks e adalah 0.0
jika baris dikalikan dengan kelipatan maka hasilnya akan 0
determinan dari matriks f adalah 0.0
determinan dari matriks g adalah 24.0
determinan dari matriks a adalah -5.0
determinan dari matriks h adalah -20.0
determinan dari matriks i adalah -10.0

mengalikan salah satu kolom 
determinan dari matriks j adalah -10.0


In [2]:
a=np.array([[3,4],[2,1]])
print("determinan dari matriks a adalah",det(a).round())
a1=np.array([[4,1],[2,1]])
print("determinan dari matriks a1 adalah",det(a1).round())
a2=np.array([[7,5],[2,1]])
print("determinan dari matriks a2 adalah",det(a2).round())#det (a2)=det (a) + det(a1)

determinan dari matriks a adalah -5.0
determinan dari matriks a1 adalah 2.0
determinan dari matriks a2 adalah -3.0


In [3]:
print("mencari determinan dari matriks segitiga atas")
upmatriks=np.array([[1,3,2],[0,2,2],[0,0,1]])
print("determinan dari matriks up matriks adalah",det(upmatriks))
up2=np.array([[2,1,3],[0,4,2],[0,0,1]])
print("determinan dari matriks up2 adalah",det(up2).round()) #mencari determinannya dengan mengalikan elemen diagonalnya -> 2.4.1=8

mencari determinan dari matriks segitiga atas
determinan dari matriks up matriks adalah 2.0
determinan dari matriks up2 adalah 8.0


In [4]:
print("mencari determinan dari matriks segitiga bawah")
undermatriks=np.array([[1,0,0],[1,2,0],[1,2,1]])
print("determinan dari matriks undermatriks adalah",det(undermatriks))
under2 = np.array([[1,0,0],[2,4,0],[1,3,2]])
print("determinan dari matriks under2 adalah",det(under2).round()) #mencari determinannya dengan mengalikan elemen diagonalnya -> 1.4.2=8

mencari determinan dari matriks segitiga bawah
determinan dari matriks undermatriks adalah 2.0
determinan dari matriks under2 adalah 8.0


In [5]:
print("determinan matriks C = det(A)det(B)")
cobaA = np.array([[2,1],[1,1]])
print("determinan dari matriks cobaA adalah",det(cobaA))
cobaB = np.array([[1,1],[1,1]])
print("determinan dari matriks cobaB adalah",det(cobaB))
cobaC = np.array([[3,3],[2,2]])
print("determinan dari matriks cobaC adalah",det(cobaC))
print("terbukti bahwa det(cobaC) = det(cobaA)det(cobaB)")

determinan matriks C = det(A)det(B)
determinan dari matriks cobaA adalah 1.0
determinan dari matriks cobaB adalah 0.0
determinan dari matriks cobaC adalah 0.0
terbukti bahwa det(cobaC) = det(cobaA)det(cobaB)


# COFACTOR

Adalah sebuah angka yang diperoleh dari elemen-elemen dalam matriks dengan cara tertenttu, yang sering digunakan dalam perhitungan determinan dan invers matriks. Cofactor dari $C_{ij}$ dari elemen $a_{ij}$ dalam sebuah matriks adalah hasil kali dari determinan submatriks yang diperoleh dengan menghapus baris $i$ dan kolom $j$ dari mattriks asli, dikalikan dengan $(-1)^{i+j}$


## Menghitung Invers Matriks 5 X 5 dengan cofactor

Kita bisa mencari invers matriks dengan menemukan determinan dan kofaktornya. Berikut langkah-langkah menghitung kofaktor:

1. Pilih elemen aij
2. Hapus baris dan kolom, baris ke-$i$ dan kolom ke-$j$ dari matriks untuk mendapatkan submatriks
3. Bentuk sub matriks, submatriks ini didapat dari elemen-elemen yang tersisa setelah menghapus baris dan kolom tersebut
4. Hitung determinan submatriks
5. Kalikan dengan $(-1)^{i+j}$, cofaktor $C_{ij}$ adalah hasil kali determinan submatriks dengan $(-1)^{i+j}$

Secara matematis, kofaktor Cij dari elemen aij adalah

$C_{ij} = (-1)^{i+j} .det(M_{ij})$

dimana det $(M_{ij})$ adalah determinan submatriks yang diperoleh dengan menghapus baris $i$ dan kolom $j$ dari matriks asli.

Rumus det pick row $i:$

$$det A = a_{i1}c_{i1}+a_{i2}c_{i2}+...+a_{in}c_{in}$$

Rumus det pick column $j:$

$$det A = a_{1j}c_{1j}+a_{2j}c_{2j}+...+a_{nj}c_{nj}$$

Rumus invers matrix:

$$A^-1= (1/det A) * adj(A) $$

Adjoin:

$$adj(A)=(kof(A))^T$$

(adj(A)) adalah hasil dari tranpose dari setiap cofactor-cofactor matriks

Contoh matriks 5X5:

$$
\begin{equation*}
Y=
\begin{bmatrix}
2 & 1 & 3 & 1 & 2 \\
1 & 1 & 6 & 1 & 3 \\
2 & -2 & 5 & 4 & 1 \\
1 & 2 & 1 & 3 & 1 \\
3 & 2 & 3 & 2 & 1 \\
\end{bmatrix}
\end{equation*}
$$

Berikut penyelesaian matriks di atas dengan memanggil library numpy:

In [27]:
import numpy as np

#fungsi mencari determinan
def det(matriks):
    return np.linalg.det(matriks)
#fungsi untuk menghitung kofaktor
def hitung_kofaktor(matrix):
    def cofactor(matrix, i, j):
        minor = np.delete(np.delete(matrix, i, axis=0), j, axis=1)
        cof = (-1) ** (i + j) * np.linalg.det(minor)
        return cof
    rows, cols = matrix.shape
    cofactor_matrix = np.zeros((rows, cols))
    for i in range(rows):
        for j in range(cols):
            cofactor_matrix[i, j] = cofactor(matrix, i, j)
    return cofactor_matrix
#fungsi mencari invers
def invers (matriks):
  return np.linalg.inv(matriks)

Y = np.array ([[2,1,3,1,2],[1,1,6,1,3],[2,-2,5,4,1],[1,2,1,3,1],[3,2,3,2,1]])

#mencari sub matriks yang didapat dari elemen-elemen yang tersisa setelah menghapus baris dan kolom
#baris 1
Y11 = np.array([[1,6,1,3],[-2,5,4,1],[2,1,3,1],[2,3,2,1]])
Y12 = np.array([[1,6,1,3],[2,5,4,1],[1,1,3,1],[3,3,2,1]])
Y13 = np.array([[1,1,1,3],[2,-2,4,1],[1,2,3,1],[3,2,2,1]])
Y14 = np.array([[1,1,6,3],[2,-2,5,1],[1,2,1,1],[3,2,3,1]])
Y15 = np.array([[1,1,6,1],[2,-2,5,4],[1,2,1,3],[3,2,3,2]])
#baris 2
Y21 = np.array([[1,3,1,2],[-2,5,4,1],[2,1,3,1],[2,3,2,1]])
Y22 = np.array([[2,3,1,2],[2,5,4,1],[1,1,3,1],[3,3,2,1]])
Y23 = np.array([[2,1,1,2],[2,-2,4,1],[1,2,3,1],[3,2,2,1]])
Y24 = np.array([[2,1,3,2],[2,-2,5,1],[1,2,1,1],[3,2,3,1]])
Y25 = np.array([[2,1,3,1],[2,-2,5,4],[1,2,1,3],[3,2,3,2]])
#baris 3
Y31 = np.array([[1,3,1,2],[1,6,1,3],[2,1,3,1],[2,3,2,1]])
Y32 = np.array([[2,3,1,2],[1,6,1,3],[1,1,3,1],[3,3,2,1]])
Y33 = np.array([[2,1,1,2],[1,1,1,3],[1,2,3,1],[3,2,2,1]])
Y34 = np.array([[2,1,3,2],[1,1,6,3],[1,2,1,1],[3,2,3,1]])
Y35 = np.array([[2,1,3,1],[1,1,6,1],[1,2,1,3],[3,2,3,2]])
#baris 4
Y41 = np.array([[1,3,1,2],[1,6,1,3],[-2,5,4,1],[2,3,2,1]])
Y42 = np.array([[2,3,1,2],[1,6,1,3],[2,5,4,1],[3,3,2,1]])
Y43 = np.array([[2,1,1,2],[1,1,1,3],[2,-2,4,1],[3,2,2,1]])
Y44 = np.array([[2,1,3,2],[1,1,6,3],[2,-2,5,1],[3,2,3,1]])
Y45 = np.array([[2,1,3,1],[1,1,6,1],[2,-2,5,4,],[3,2,3,2]])
#baris 5
Y51 = np.array([[1,3,1,2],[1,6,1,3],[-2,5,4,1],[2,1,3,1]])
Y52 = np.array([[2,3,1,2],[1,6,1,3],[2,5,4,1],[1,1,3,1]])
Y53 = np.array([[2,1,1,2],[1,1,1,3],[2,-2,4,1],[1,2,3,1]])
Y54 = np.array([[2,1,3,2],[1,1,6,3],[2,-2,5,1],[1,2,1,1]])
Y55 = np.array([[2,1,3,1],[1,1,6,1],[2,-2,5,4],[1,2,1,3]])

In [9]:
#Kemudian kita mencari determinan dari masing-masing sub matriks
#baris 1
det11 = det(Y11)
det12 = det(Y12)
det13 = det(Y13)
det14 = det(Y14)
det15 = det(Y15)
#baris 2
det21 = det(Y21)
det22 = det(Y22)
det23 = det(Y23)
det24 = det(Y24)
det25 = det(Y25)
#baris 3
det31 = det(Y31)
det32 = det(Y32)
det33 = det(Y33)
det34 = det(Y34)
det35 = det(Y35)
#baris 4
det41 = det(Y41)
det42 = det(Y42)
det43 = det(Y43)
det44 = det(Y44)
det45 = det(Y45)
#baris 5
det51 = det(Y51)
det52 = det(Y52)
det53 = det(Y53)
det54 = det(Y54)
det55 = det(Y55)

In [19]:
#Setelah mengetahui determinan dari masing-masing sub matriks kita kemudian mencari kofaktornya
#baris 1
c11 = (-1)**(1+1) * det11
c12 = (-1)**(1+2) * det12
c13 = (-1)**(1+3) * det13
c14 = (-1)**(1+4) * det14
c15 = (-1)**(1+5) * det15
#baris 2
c21 = (-1)**(2+1) * det21
c22 = (-1)**(2+2) * det22
c23 = (-1)**(2+3) * det23
c24 = (-1)**(2+4) * det24
c25 = (-1)**(2+5) * det25
#baris 3
c31 = (-1)**(3+1) * det31
c32 = (-1)**(3+2) * det32
c33 = (-1)**(3+3) * det33
c34 = (-1)**(3+4) * det34
c35 = (-1)**(3+5) * det35
#baris 4
c41 = (-1)**(4+1) * det41
c42 = (-1)**(4+2) * det42
c43 = (-1)**(4+3) * det43
c44 = (-1)**(4+4) * det44
c45 = (-1)**(4+5) * det45
#baris 5
c51 = (-1)**(5+1) * det51
c52 = (-1)**(5+2) * det52
c53 = (-1)**(5+3) * det53
c54 = (-1)**(5+4) * det54
c55 = (-1)**(5+5) * det55

#mari kita cek apakah kofaktornya sudah benar atau belum
#kofaktor memakai fungsi di atas
cofactor_matrix = hitung_kofaktor(Y)
print("Matriks Kofaktor memakai fungsi:")
print(cofactor_matrix,"\n")
print("="*45)
print("\nMatriks Kofaktor dari hasil pertungan manual:")
cofactor = np.array([[c11,c12,c13,c14,c15],[c21,c22,c23,c24,c25],[c31,c32,c33,c34,c35],[c41,c42,c43,c44,c45],[c51,c52,c53,c54,c55]])
print(cofactor)
print("\nHasil dari keduanya sama, ini menunjukkan bahwa kita bisa menggunakan hitung manual, tetapi akan lebih menyingkat waktu jika kita menggunakan fungsi")

Matriks Kofaktor memakai fungsi:
[[ -82.   69.   87.   10. -173.]
 [  54.  -33.  -49.   10.   31.]
 [  -6.   32.   -4.  -20.    6.]
 [  36.  -22.   24.  -50.  -36.]
 [ -28.  -49.  -47.   20.  113.]] 


Matriks Kofaktor dari hasil pertungan manual:
[[ -82.   69.   87.   10. -173.]
 [  54.  -33.  -49.   10.   31.]
 [  -6.   32.   -4.  -20.    6.]
 [  36.  -22.   24.  -50.  -36.]
 [ -28.  -49.  -47.   20.  113.]]

Hasil dari keduanya sama, ini menunjukkan bahwa kita bisa menggunakan hitung manual, tetapi akan lebih menyingkat waktu jika kita menggunakan fungsi


In [20]:
#selanjutnya kita menempat setiap elemen dari matriks aslinya di dalam sebuah variable baru
a11 = Y[0][0]
a12 = Y[0][1]
a13 = Y[0][2]
a14 = Y[0][3]
a15 = Y[0][4]
a21 = Y[1][0]
a22 = Y[1][1]
a23 = Y[1][2]
a24 = Y[1][3]
a25 = Y[1][4]
a31 = Y[2][0]
a32 = Y[2][1]
a33 = Y[2][2]
a34 = Y[2][3]
a35 = Y[2][4]
a41 = Y[3][0]
a42 = Y[3][1]
a43 = Y[3][2]
a44 = Y[3][3]
a45 = Y[3][4]
a51 = Y[4][0]
a52 = Y[4][1]
a53 = Y[4][2]
a54 = Y[4][3]
a55 = Y[4][4]

In [25]:
#Setelah itu, kita mecari determinan dari masing masing barisnya
#baris 1
det1 = a11*c11 + a12*c12 + a13*c13 + a14*c14 + a15*c15
print(f"det Y baris 1 = {det1} atau bisa dibulatkan menjadi {det1.round()}")
#baris 2
det2 = a21*c21 + a22*c22 + a23*c23 + a24*c24 + a25*c25
print(f"det Y baris 2 = {det2} atau bisa dibulatkan menjadi {det2.round()}")
#baris 3
det3 = a31*c31 + a32*c32 + a33*c33 + a34*c34 + a35*c35
print(f"det Y baris 3 = {det3} atau bisa dibulatkan menjadi {det3.round()}")
#baris 4
det4 = a41*c41 + a42*c42 + a43*c43 + a44*c44 + a45*c45
print(f"det Y baris 4 = {det4} atau bisa dibulatkan menjadi {det4.round()}")
#baris 5
det5 = a51*c51 + a52*c52 + a53*c53 + a54*c54 + a55*c55
print(f"det Y baris 5 = {det5} atau bisa dibulatkan menjadi {det5.round()}")

print("\nMenghitung matriks determinan dengan menggunakan fungsi:")
det_Y = det(Y)
print(det_Y,"atau bisa dibulatkan menjadi", det_Y.round())

print("\nIni menunjukkan bahwa kita menghitung salah satu barisnya saja, karna hasilnya sama dan sama juga dengan mencari determinan menggunakan fungsi")

det Y baris 1 = -170.0000000000001 atau bisa dibulatkan menjadi -170.0
det Y baris 2 = -170.00000000000003 atau bisa dibulatkan menjadi -170.0
det Y baris 3 = -170.00000000000006 atau bisa dibulatkan menjadi -170.0
det Y baris 4 = -169.99999999999997 atau bisa dibulatkan menjadi -170.0
det Y baris 5 = -170.00000000000006 atau bisa dibulatkan menjadi -170.0

Menghitung matriks determinan dengan menggunakan fungsi:
-170.00000000000006 atau bisa dibulatkan menjadi -170.0

Ini menunjukkan bahwa kita menghitung salah satu barisnya saja, karna hasilnya sama dan sama juga dengan mencari determinan menggunakan fungsi


In [40]:
#pembuktian bahwa matriks
print("Matriks Kofaktor:")
print(cofactor_matrix,"\n")
Trans_Kof = cofactor.transpose()
print(f"Transpose Matrix dari kofaktornya = \n{Trans_Kof}")
print()
inversY = 1 / det1* Trans_Kof
print(f"Hasil Invers Matrix dari cofactor adalah = \n{inversY.round(1)}")
print("\nKita bandingkan jika mencari invers langsung dari matriks asal bukan dari cofactor matriks yang telah ditranpose kemudian diinverskan")
print(f"\nInvers dari matriks asal adalah\n {invers(Y).round(1)}")
print("\nDari keduanya menunjukkan hasil yang sama yang berarti kita boleh invers dari cofactor matriks yang telah ditranpose kemudian diinverskan ataupun dari matriks asalnya")

Matriks Kofaktor:
[[ -82.   69.   87.   10. -173.]
 [  54.  -33.  -49.   10.   31.]
 [  -6.   32.   -4.  -20.    6.]
 [  36.  -22.   24.  -50.  -36.]
 [ -28.  -49.  -47.   20.  113.]] 

Transpose Matrix dari kofaktornya = 
[[ -82.   54.   -6.   36.  -28.]
 [  69.  -33.   32.  -22.  -49.]
 [  87.  -49.   -4.   24.  -47.]
 [  10.   10.  -20.  -50.   20.]
 [-173.   31.    6.  -36.  113.]]

Hasil Invers Matrix dari cofactor adalah = 
[[ 0.5 -0.3  0.  -0.2  0.2]
 [-0.4  0.2 -0.2  0.1  0.3]
 [-0.5  0.3  0.  -0.1  0.3]
 [-0.1 -0.1  0.1  0.3 -0.1]
 [ 1.  -0.2 -0.   0.2 -0.7]]

Kita bandingkan jika mencari invers langsung dari matriks asal bukan dari cofactor matriks yang telah ditranpose kemudian diinverskan

Invers dari matriks asal adalah
 [[ 0.5 -0.3  0.  -0.2  0.2]
 [-0.4  0.2 -0.2  0.1  0.3]
 [-0.5  0.3  0.  -0.1  0.3]
 [-0.1 -0.1  0.1  0.3 -0.1]
 [ 1.  -0.2 -0.   0.2 -0.7]]

Dari keduanya menunjukkan hasil yang sama yang berarti kita boleh invers dari cofactor matriks yang telah ditranpo