# Determinant


## sifat sifat determinan

1. determinan dari matriks identitas = 1
2. jika suatu matriks dikalikan dengan konstanta maka rumus dekterminannya:

    constanta^berapa baris atau kolom yang dikalikan (hasil determinan dari matriks asalnya)

    atau
    
    K^n(det(A))
3. jika matriks segitiga atas atau segitiga bawah dicari determinannya maka akan menghasilkan perkalian dari elemen di diagonalnya
4. det(AB) = det(A).det(B)
5. det(A)^2 = det(A).det(A)
6. det(A^T) = det(A)

##syarat mencari determinan matriks :
Hanya dapat dilakukan pada matriks bujur sangkar atau matriks persegi atau matriks yang mempunyai baris = kolom

In [36]:
import numpy as np


#fungsi mencari determinan
def det(matriks):
    return np.linalg.det(matriks)

print("Membuktikan bahwa determinan dari matriks identitas adalah 1")
I=np.array([[1,0,0],[0,1,0],[0,0,1]])
print('Matriks A =\n', I)
print("determinan dari matriks i adalah",det(I))

print("perubahan baris pada matriks identitas untuk mencari determinannya")
I2=np.array([[1,0,0],[0,0,1],[0,1,0]])
print("determinan dari matriks i setelah diubah pertama kali adalah",det(I2))
I3=np.array([[0,1,0],[0,0,1],[1,0,0]])
print("determinan dari matriks i setelah diubah kedua kali adalah",det(I3),"\n")

print("mencari determinan c")
c = np.array([[1,2,1],[3,1,2],[2,1,2]])
print("determinan dari matriks c adalah",det(c).round())
d = np.array([[3,1,2],[1,2,1],[2,1,2]])
print("determinan dari matriks c setelah diubah pertama kali adalah",det(d).round())
e = np.array([[1,2,1],[2,4,2],[2,1,2]])
print("determinan dari matriks e adalah",det(e).round())
print("jika baris dikalikan dengan kelipatan maka hasilnya akan 0")
f = np.array([[1,2,1],[2,4,2],[2,4,3]])
print("determinan dari matriks f adalah",det(f).round())
g = np.array([[6,2,4],[2,4,2],[4,2,4]])
print("determinan dari matriks g adalah",det(g).round())#2^3(3)
a=np.array([[3,4],[2,1]])
print("determinan dari matriks a adalah",det(a).round())
h=np.array([[6,8],[4,2]])
print("determinan dari matriks h adalah",det(h).round()) #2^2(-5)=-20
i=np.array([[6,8],[2,1]])
print("determinan dari matriks i adalah",det(i).round()) #jika hanya satu baris saja c det(a) = 2(-5) = -10

print("\nmengalikan salah satu kolom ")
j=np.array([[6,4],[4,1]])
print("determinan dari matriks j adalah",det(j).round())#hasilnya bakal sama dengan yang salah satu baris saja yang dikalikan

Membuktikan bahwa determinan dari matriks identitas adalah 1
Matriks A =
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
determinan dari matriks i adalah 1.0
perubahan baris pada matriks identitas untuk mencari determinannya
determinan dari matriks i setelah diubah pertama kali adalah -1.0
determinan dari matriks i setelah diubah kedua kali adalah 1.0 

mencari determinan c
determinan dari matriks c adalah -3.0
determinan dari matriks c setelah diubah pertama kali adalah 3.0
determinan dari matriks e adalah 0.0
jika baris dikalikan dengan kelipatan maka hasilnya akan 0
determinan dari matriks f adalah 0.0
determinan dari matriks g adalah 24.0
determinan dari matriks a adalah -5.0
determinan dari matriks h adalah -20.0
determinan dari matriks i adalah -10.0

mengalikan salah satu kolom 
determinan dari matriks j adalah -10.0


In [39]:
a=np.array([[3,4],[2,1]])
print("determinan dari matriks a adalah",det(a).round())
a1=np.array([[4,1],[2,1]])
print("determinan dari matriks a1 adalah",det(a1).round())
a2=np.array([[7,5],[2,1]])
print("determinan dari matriks a2 adalah",det(a2).round())#det (a2)=det (a) + det(a1)

determinan dari matriks a adalah -5.0
determinan dari matriks a1 adalah 2.0
determinan dari matriks a2 adalah -3.0


In [40]:
print("mencari determinan dari matriks segitiga atas")
upmatriks=np.array([[1,3,2],[0,2,2],[0,0,1]])
print("determinan dari matriks up matriks adalah",det(upmatriks))
up2=np.array([[2,1,3],[0,4,2],[0,0,1]])
print("determinan dari matriks up2 adalah",det(up2).round()) #mencari determinannya dengan mengalikan elemen diagonalnya -> 2.4.1=8

mencari determinan dari matriks segitiga atas
determinan dari matriks up matriks adalah 2.0
determinan dari matriks up2 adalah 8.0


In [41]:
print("mencari determinan dari matriks segitiga bawah")
undermatriks=np.array([[1,0,0],[1,2,0],[1,2,1]])
print("determinan dari matriks undermatriks adalah",det(undermatriks))
under2 = np.array([[1,0,0],[2,4,0],[1,3,2]])
print("determinan dari matriks under2 adalah",det(under2).round()) #mencari determinannya dengan mengalikan elemen diagonalnya -> 1.4.2=8

mencari determinan dari matriks segitiga bawah
determinan dari matriks undermatriks adalah 2.0
determinan dari matriks under2 adalah 8.0


In [42]:
print("determinan matriks C = det(A)det(B)")
cobaA = np.array([[2,1],[1,1]])
print("determinan dari matriks cobaA adalah",det(cobaA))
cobaB = np.array([[1,1],[1,1]])
print("determinan dari matriks cobaB adalah",det(cobaB))
cobaC = np.array([[3,3],[2,2]])
print("determinan dari matriks cobaC adalah",det(cobaC))

determinan matriks C = det(A)det(B)
determinan dari matriks cobaA adalah 1.0
determinan dari matriks cobaB adalah 0.0
determinan dari matriks cobaC adalah 0.0
