# Eigenvalues dan Eigenvectors

- Eigenvalues (Nilai Eigen):

Eigenvalues adalah nilai khusus yang terkait dengan sebuah matriks persegi. Untuk matriks $A$, nilai eigen didefinisikan sebagai nilai $λ$ yang memenuhi persamaan:
$$Av=λv$$
di mana $v$ adalah eigenvector yang terkait dengan nilai eigen $λ$. Dalam hal ini, matriks $A$ bertindak seperti operator linier yang mengubah vektor $v$ hanya dengan mengalikannya dengan nilai eige-n $λ$. Eigenvalues sangat penting dalam menganalisis sifat-sifat matriks, seperti stabilitas sistem dinamis.

- Eigenvectors (Vektor Eigen):

Eigenvectors adalah vektor non-nol yang, ketika dikalikan dengan matriks, hanya mengalami perubahan skalar. Dengan kata lain, sebuah vektor
$v$ adalah eigenvector dari matriks $A$ jika perkalian $Av$ hanya menghasilkan skalar dari $v$, yaitu $λv$, di mana $λ$ adalah eigenvalue yang sesuai. Eigenvectors menunjukkan arah di mana transformasi oleh matriks dilakukan tanpa memutar, hanya mengubah panjang vektor.

Kombinasi dari eigenvalues dan eigenvectors memungkinkan kita untuk memahami transformasi yang dilakukan oleh matriks

Code 1

In [1]:
import numpy as np
mat = np.mat([[1,4],[2,3]])
print (mat)
print(' ')
evalue, evect = np.linalg.eig(mat)
print (evalue)
print(' ')
print(evect.round())

[[1 4]
 [2 3]]
 
[-1.  5.]
 
[[-1. -1.]
 [ 0. -1.]]


## (A - λI) x = 0 Ax = λx

Merupakan matriks singular (matriks yang determinannya = 0)

In [4]:
import numpy as np

# Definisikan matriks A
A = np.array([[1,4],[2,3]])

# Fungsi untuk menghitung determinan matriks (A - λI)
def determinan(A, lamb):
    return np.linalg.det(A - lamb * np.identity(A.shape[0]))

# Fungsi untuk menemukan eigenvalues (nilai λ yang membuat determinan = 0)
def find_eigenvalues(A):
    # Membuat fungsi lambda untuk determinan matriks (A - λI)
    f = lambda lamb: determinan(A, lamb)
    # Mencari nilai λ yang membuat determinan matriks (A - λI) mendekati 0
    eigenvalues = []
    for lamb in np.linspace(-10, 10, 1000):  # Rentang pencarian nilai λ
        if np.isclose(f(lamb), 0, atol=1e-3):  # Toleransi mendekati 0
            eigenvalues.append(lamb)
    return np.unique(eigenvalues)  # Mengembalikan nilai λ unik

# Menghitung eigenvalues
eigenvalues = find_eigenvalues(A)
print("Eigenvalues:", eigenvalues)

# Menghitung eigenvectors untuk setiap eigenvalue
for lamb in eigenvalues:
    # (A - λI)x = 0
    eigenvector = np.linalg.null_space(A - lamb * np.identity(A.shape[0]))
    print(f"Eigenvector untuk eigenvalue {lamb}:\n", eigenvector)

Eigenvalues: []


Code 2

In [5]:
import numpy as np
from numpy.linalg import eig

# Definisikan matriks A
A = np.array([[1,4],[2,3]])

# Hitung eigenvalues dan eigenvectors
eigenvalues, eigenvectors = eig(A)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors.round())

Eigenvalues: [-1.  5.]
Eigenvectors:
 [[-1. -1.]
 [ 0. -1.]]


Karna hasil dri code 1 atau 2 sama, kita bisa bebas memilih menggunakan yang mana