#Tugas 3
## Matriks invers

Matriks yang jika dikalikan dengan matriks asalnya, akan menghasilkan metriks identitas.
Dan sering digunakan dalam pemecahan sistem persamaan linier.

AA^-1 = A^-1 x A = I

I adalah matriks identitas yang memiliki elemen-elemen diagonal bernilai 1 dan elemen-elemen lainnya bernilai 0. Matriks invers ini hanya ada untuk matriks persegi yang tidak singular, determinannya tidak nol. Contoh :

- Matriks dengan ordo(2 x2):

$$
\begin{equation*}
A=
\begin{bmatrix}
a&b\\
c&d
\end{bmatrix}
\end{equation*}
$$
$$
\begin{align*}
A^-1\ =\frac{1}{ad-bc}
\begin{bmatrix}
d&-b\\
-c&a
\end{bmatrix}
\end{align*}
$$

- Matriks dengan ordo (3 x3):

$$
\begin{equation*}
A=
\begin{bmatrix}
a&b&c\\
d&e&f\\
g&h&i\
\end{bmatrix}
\end{equation*}
$$
$$
\begin{equation*}
A^-1=\frac{1}{aei + bfg + cdh - gec - hfa - idb}
Adj A
\end{equation*}
$$


In [ ]:
import numpy as np

a=np.array([[2,-1],[-3,2]])
print('Matriks A =\n', a)

Matriks A =
 [[ 2 -1]
 [-3  2]]


Contoh matriks dengan ordo (2 x2):

$$
\begin{equation*}
A=
\begin{bmatrix}
2&-1\\
-3&2
\end{bmatrix}
\end{equation*}
$$

Untuk mencari inversnya dapat dilakukan dengan mencari determinannya terlebih dahulu, menggunakan rumus di bawah ini.

det A = ad - bc

Berikut penyelesaian determinannya:

det A = (2 x 2) - (-1 x (-3)) = 4 - 3 = 1

Setelah ditemukan nilai determinannya, langkah selanjutnya yaitu masukkan nilai determinan pada rumus invers matriks dengan ordo (2 x 2)

$$
\begin{equation*}
A^-1=\frac{1}{det A}
\begin{bmatrix}
d&-b\\
-c&a
\end{bmatrix}
\end{equation*}
$$

Berikut penyelesaian Matriks invers nya:

$$
\begin{equation*}
A^-1=\frac{1}{1}
\begin{bmatrix}
2&1\\
3&2
\end{bmatrix}
=
\begin{bmatrix}
2&1\\
3&2
\end{bmatrix}
\end{equation*}
$$


In [ ]:
#Berikut Codenya:
import numpy as np

a=np.array([[(1/1)*2, (1/1)*1],[(1/1)*3, (1/1)*2]])
print('Matriks A^-1 =\n', a)

Matriks A^-1 =
 [[2. 1.]
 [3. 2.]]


###Sifat-sifat Matriks invers
1. Hanya dimiliki oleh matriks persegi karna memiliki kolom dan baris yanng sama.
2. Hanya ada matriks non-singular. Determinannya tidak sama dengan 0.
3. Unik : Setiap matriks hanya memiliki satu matriks invers
4. Invers dari invers : Jika Z memiliki invers, maka inversnya adalah matriks Z itu sendiri. $\begin{align*}(Z^-1)^-1=Z\end{align*}$
5. Invers dari hasil kali : Jika Y dan Z adalah matriks yang memiliki invers, maka hasil kali AB juga memiliki invers, dan invernya adalah hasil kali invers secara terbalik. $\begin{align*}(YZ)^-1=(Z^-1)Y^-1\end{align*}$
6. Invers dari tranpose : jika Z merupakan matriks persegi yang memiliki invers dari tranposenya adalah tranpose dari inversnya. $\begin{align*}(Z^T)^-1=(Z^-1)^T\end{align*}$
7. Invers dari matriks identitas : Invers dari matriks identitas I adalah I itu sendiri


In [ ]:
import numpy as np

a=np.array([[4,5,4],[2,1,-3],[-1,-2,4]])
i = np.array([[1,0,0],[0,1,0],[0,0,1]])

print('AI=\n',a@i)
print('IA=\n',i@a)
print('A=\n',a)

AI=
 [[ 4  5  4]
 [ 2  1 -3]
 [-1 -2  4]]
IA=
 [[ 4  5  4]
 [ 2  1 -3]
 [-1 -2  4]]
A=
 [[ 4  5  4]
 [ 2  1 -3]
 [-1 -2  4]]


###Mencari Invers Dengan Eliminasi Gauss Jordan Elimination
Berikut contoh matriks A:
$$
\begin{equation*}
A=
\begin{bmatrix}
6&5\\
8&10
\end{bmatrix}
\end{equation*}
$$

Eliminasi Gauss Jordan dilakukan dengan menempatkan matriks A di sebelah kiri dan matriks identitas(I) di sebelah kanan. Kedua matriks ini dipisahkan dengan garis putus-putus. Seperti berikut:

$$
\begin{equation*}
A=
\begin{bmatrix}
6&5& | &1&0 \\
8&10& | &0&1
\end{bmatrix}
\end{equation*}
$$

Berikut penyelesaian menggunakan Eliminasi Gauss Jordan Elimination:

1. Bagilah baris 1 dengan 6 [R1 = (1/6) R1]

$$
\begin{equation*}
A=
\begin{bmatrix}
1&5/6& | &1/6&0 \\
8&10& | &0&1
\end{bmatrix}
\end{equation*}
$$

2. [R2 = R2 - 8R1]

$$
\begin{equation*}
A=
\begin{bmatrix}
1&5/6& | &1/6&0 \\
0&10/3& | &-4/3&1
\end{bmatrix}
\end{equation*}
$$

3. [R2 = (3/10)R2]

$$
\begin{equation*}
A=
\begin{bmatrix}
1&5/6& | &1/6&0 \\
0&1& | &-2/5&3/10
\end{bmatrix}
\end{equation*}
$$

4. [R1 = R1 - (5/6)R2]

$$
\begin{equation*}
A=
\begin{bmatrix}
1&0& | &1/2&-1/4 \\
0&1& | &-2/5&3/10
\end{bmatrix}
\end{equation*}
$$


In [ ]:
import numpy as np

def invers_matriks_2x2(A):
    # Periksa apakah matriks A dapat diinverskan
    if np.linalg.det(A) == 0:
        print("Matriks tidak dapat diinverskan karena determinan = 0.")
        return None

    # Buat matriks identitas berukuran 2x2
    I = np.eye(2)

    # Gabungkan matriks A dan matriks identitas
    aug_matrix = np.hstack((A, I))

    # Lakukan operasi baris elementer untuk mengubah matriks A menjadi matriks identitas
    for i in range(2):
        # Bagi baris ke-i dengan elemen diagonal
        pivot = aug_matrix[i, i]
        aug_matrix[i, :] /= pivot
        # Kurangi baris lain dengan kelipatan baris ke-i
        for j in range(2):
          if j != i:
            factor = aug_matrix[j, i]
            aug_matrix[j, :] -= factor * aug_matrix[i, :]

     # Matriks invers berada di sisi kanan matriks augmentasi
    invers_A = aug_matrix[:, 2:]

    return invers_A

# Contoh penggunaan
A = np.array([[6, 5], [8, 10]])
invers_A = invers_matriks_2x2(A)
print("Matriks A:")
print(A)
print("\nMatriks invers A:")
print(invers_A)


Matriks A:
[[ 6  5]
 [ 8 10]]

Matriks invers A:
[[ 0.5  -0.25]
 [-0.4   0.3 ]]


### Soal Eliminasi Persamaan Linier

(membuat contoh soal persamaan linier 6 variable)

$$
\\3a + 2b - c + 4d - 5e + 6f = 10\\
2a - b + 3c + 4d - 2e + 5f = 20\\
a + 4b - 2c + 3d + e + 2f = 30\\
4a - b + 2c + 5d + 3e - 4f = 40\\
a + 3b + 2c + 4d - e + 3f = 50\\
2a + 2b - 3c + d - 4e + 2f = 60\\
$$

Matriks augmented dari sistem persamaan ini :

$$
\begin{bmatrix}
3 & 2 & -1 & 4 & -5 & 6 &|& 10\\
2 & -1 & 3 & 4 & -2 & 5 &|& 20\\
1 & 4 & -2 & 3 & 1 & 2 &|& 30\\
4 & -1 & 2 & 5 & 3 & -4 &|& 40\\
1 & 3 & 2 & 4 & -1 & 3 &|& 50\\
2 & 2 & -3 & 1 & -4 & 2 &|& 60\\
\end{bmatrix}
$$

Menulis matriks augemented:

$$
\begin{bmatrix}
3 & 2 & -1 & 4 & -5 & 6 & | & 1 & 0 & 0 & 0 & 0 & 0 \\
2 & -1 & 3 & 4 & -2 & 5 & | & 0 & 1 & 0 & 0 & 0 & 0 \\
1 & 4 & -2 & 3 & 1 & 2 & | & 0 & 0 & 1 & 0 & 0 & 0 \\
4 & -1 & 2 & 5 & 3 & -4 & | & 0 & 0 & 0 & 1 & 0 & 0 \\
1 & 3 & 2 & 4 & -1 & 3  & | & 0 & 0 & 0 & 0 & 1 & 0 \\
2 & 2 & -3 & 1 & -4 & 2 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$

Berikut penyelesaian dari matriks di atas menggunakan guss jordan:

1. Tukar kolom 1 dengan kolom 3

$$
\begin{bmatrix}
1 & 4 & -2 & 3 & 1 & 2 & | & 0 & 0 & 1 & 0 & 0 & 0 \\
2 & -1 & 3 & 4 & -2 & 5 & | & 0 & 1 & 0 & 0 & 0 & 0 \\
3 & 2 & -1 & 4 & -5 & 6 & | & 1 & 0 & 0 & 0 & 0 & 0 \\
4 & -1 & 2 & 5 & 3 & -4 & | & 0 & 0 & 0 & 1 & 0 & 0 \\
1 & 3 & 2 & 4 & -1 & 3  & | & 0 & 0 & 0 & 0 & 1 & 0 \\
2 & 2 & -3 & 1 & -4 & 2 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$

2. [R2 = R2 - 2 R1]

$$
\begin{bmatrix}
1 & 4 & -2 & 3 & 1 & 2 & | & 0 & 0 & 1 & 0 & 0 & 0 \\
0 & -9 & 7 & -2 & -4 & 1 & | & 0 & 1 & -2 & 0 & 0 & 0 \\
3 & 2 & -1 & 4 & -5 & 6 & | & 1 & 0 & 0 & 0 & 0 & 0 \\
4 & -1 & 2 & 5 & 3 & -4 & | & 0 & 0 & 0 & 1 & 0 & 0 \\
1 & 3 & 2 & 4 & -1 & 3  & | & 0 & 0 & 0 & 0 & 1 & 0 \\
2 & 2 & -3 & 1 & -4 & 2 & | & 0 & 0 & 0 & 0 & 0 & 1 \
\end{bmatrix}
$$

3. [R3 = R3 - 3 R1]
   
   [R4 = R4 - 4 R1]

   [R5 = R5 - R1]

   [R6 = R6 - 2 R1]

$$
\begin{bmatrix}
1 & 4 & -2 & 3 & 1 & 2 & | & 0 & 0 & 1 & 0 & 0 & 0 \\
0 & -9 & 7 & -2 & -4 & 1 & | & 0 & 1 & -2 & 0 & 0 & 0 \\
0 & 10 & 5 & -5 & -8 & 0 &  | & 1 & 0 & -3 & 0 & 0 & 0 \\
0 & -17 & 10 & -7 & -1 & -12 & | & 0 & 0 & -4 & 1 & 0 & 0 \\
0 & -1 & 4 & 1 & -2 & 1  & | & 0 & 0 & -1 & 0 & 1 & 0 \\
0 & -6 & 1 & -5 & -6 & -2 & | & 0 & 0 & -2 & 0 & 0 & 1 \
\end{bmatrix}
$$

4. Tukar kolom 5(yang sudah dikali dengan (-)) dengan kolom 2.

$$
\begin{bmatrix}
1 & 4 & -2 & 3 & 1 & 2 & | & 0 & 0 & 1 & 0 & 0 & 0 \\
0 & 1 & -4 & -1 & 2 & -1  & | & 0 & 0 & 1 & 0 & -1 & 0 \\
0 & 10 & 5 & -5 & -8 & 0 &  | & 1 & 0 & -3 & 0 & 0 & 0 \\
0 & -17 & 10 & -7 & -1 & -12 & | & 0 & 0 & -4 & 1 & 0 & 0 \\
0 & -9 & 7 & -2 & -4 & 1 & | & 0 & 1 & -2 & 0 & 0 & 0  \\
0 & -6 & 1 & -5 & -6 & -2 & | & 0 & 0 & -2 & 0 & 0 & 1 \
\end{bmatrix}
$$

5. [R1 = R1 - ((-4) R2)]

   [R3 = R3 - 10 R2]

   [R4 = R4 - 17 R2]

   [R5 = R5 - 9 R2]

   [R6 = R6 - 6 R2]

$$
\begin{bmatrix}
1 & 0 & 14 & 7 & -7 & 6 & | & 0 & 0 & -3 & 0 & 4 & 0 \\
0 & 1 & -4 & -1 & 2 & -1  & | & 0 & 0 & 1 & 0 & -1 & 0 \\
0 & 0 & -35 & -15 & 12 & -10 &  | & 1 & 0 & 7 & 0 & -10 & 0 \\
0 & 0 & -58 & -24 & 33 & -29 & | & 0 & 0 & 13 & 1 & -17 & 0 \\
0 & 0 & -29 & -11 & 14 & 8 & | & 0 & 1 & 7 & 0 & -9 & 0  \\
0 & 0 & -23 & -11 & 6 & -8 & | & 0 & 0 & 4 & 0 & -6 & 1 \
\end{bmatrix}
$$

6. [R3 = (-1/35) R3]

$$
\begin{bmatrix}
1 & 0 & 14 & 7 & -7 & 6 & | & 0 & 0 & -3 & 0 & 4 & 0 \\
0 & 1 & -4 & -1 & 2 & -1  & | & 0 & 0 & 1 & 0 & -1 & 0 \\
0 & 0 & 1 & 3/7 & -12/35 & 2/7 &  | & -1/35 & 0 & -1/5 & 0 & 2/7 & 0 \\
0 & 0 & -58 & -24 & 33 & -29 & | & 0 & 0 & 13 & -17 & 0 & 0 \\
0 & 0 & -29 & -11 & 14 & 8 & | & 0 & 1 & 7 & 0 & -9 & 0  \\
0 & 0 & -23 & -11 & 6 & -8 & | & 0 & 0 & 4 & 0 & -6 & 1 \
\end{bmatrix}
$$

7. [R1 = R1 - 14 R3]

    [R2 = R2 - 4 R3]

    [R4 = R4 - 58 R3]

    [R5 = R5 - 29 R3]

    [R6 = R6 - 23 R3]

$$
\begin{bmatrix}
1 & 0 & 0 & 1 & -11/5 & 2 & | & 2/5 & 0 & -1/5 & 0 & 0 & 0 \\
0 & 1 & 0 & 5/7 & 22/35 & 1/7 & | & -4/35 & 0 & 1/5 & 0 & 1/7 & 0 \\
0 & 0 & 1 & 3/7 & -12/35 & 2/7 &  | & -1/35 & 0 & -1/5 & 0 & 2/7 & 0 \\
0 & 0 & 0 & 6/7 & 459/35 & -87/7 & | & -58/35 & 0 & 7/5 & 1 & -3/7 & 0 \\
0 & 0 & 0 & 10/7 & 142/35 & 2/7 & | & -29/35 & 1 & 6/5 & 0 & -5/7 & 0  \\
0 & 0 & 0 & -8/7 & -66/35 & -10/7 & | & -23/35 & 0 & -3/5 & 0 & 4/7 & 1 \
\end{bmatrix}
$$

8. [R4 = (7/6) R4]

$$
\begin{bmatrix}
1 & 0 & 0 & 1 & -11/5 & 2 & | & 2/5 & 0 & -1/5 & 0 & 0 & 0 \\
0 & 1 & 0 & 5/7 & 22/35 & 1/7 & | & -4/35 & 0 & 1/5 & 0 & 1/7 & 0 \\
0 & 0 & 1 & 3/7 & -12/35 & 2/7 &  | & -1/35 & 0 & -1/5 & 0 & 2/7 & 0 \\
0 & 0 & 0 & 1 & 157/10 & -29/2 & | & -29/15 & 0 & 49/30 & 7/6 & -1/2 & 0 \\
0 & 0 & 0 & 10/7 & 142/35 & 2/7 & | & -29/35 & 1 & 6/5 & 0 & -5/7 & 0  \\
0 & 0 & 0 & -8/7 & -66/35 & -10/7 & | & -23/35 & 0 & -3/5 & 0 & 4/7 & 1 \
\end{bmatrix}
$$

9. [R1 = R1 - R4]

   [R2 = R2 - (5/7) R4]

   [R3 = R3 - (3/7) R4]

   [R5 = R5 - (10/7) R4]

   [R6 = R6 - (-8/7) R4]

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & -35/5 & 33/2 & | & 7/3 & 0 & -11/6 & -7/6 & 1/2 & 0 \\
0 & 1 & 0 & 0 & -103/10 & 21/2 & | & 19/15 & 0 & -29/30 & -5/6 & 1/2 & 0 \\
0 & 0 & 1 & 0 & -69/10 & 13/2 &  | & 4/5 & 0 & -9/10 & -1/2 & 1/2 & 0 \\
0 & 0 & 0 & 1 & 153/10 & -29/2 & | & -29/15 & 0 & 49/30 & 7/6 & -1/2 & 0 \\
0 & 0 & 0 & 0 & -89/5 & 21 & | & 29/15 & 1 & 17/15 & -5/3 & 0 & 0  \\
0 & 0 & 0 & 0 & 78/5 & -18 & | & -43/15 & 0 & 19/15 & 4/3 & 0 & 1 \
\end{bmatrix}
$$

10. [R5 = (-5/89)R5]

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & -35/5 & 33/2 & | & 7/3 & 0 & -11/6 & -7/6 & 1/2 & 0 \\
0 & 1 & 0 & 0 & -103/10 & 21/2 & | & 19/15 & 0 & -29/30 & -5/6 & 1/2 & 0 \\
0 & 0 & 1 & 0 & -69/10 & 13/2 &  | & 4/5 & 0 & -9/10 & -1/2 & 1/2 & 0 \\
0 & 0 & 0 & 1 & 153/10 & -29/2 & | & -29/15 & 0 & 49/30 & 7/6 & -1/2 & 0 \\
0 & 0 & 0 & 0 & 1 & -105/89 & | & 29/267 & -5/89 & 17/267 & 25/267 & 0 & 0  \\
0 & 0 & 0 & 0 & 78/5 & -18 & | & -43/15 & 0 & 19/15 & 4/3 & 0 & 1 \
\end{bmatrix}
$$

11. [R1 = R1 - (-35/2) R5]

    [R2 = R2 - ((-103/10) R5)]

    [R3 = R3 - ((-69/10) R5)]

    [R4 = R4 - ((153/10) R5]

    [R6 = R6 - ((78/5) R5)]

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & -369/89 & | & 77/178 & -175/178 & -64/89 & 42/89 & 1/2 & 0 \\
0 & 1 & 0 & 0 & 0 & -147/89 & | & 79/534 & -103/178 & -83/267 & 35/267 & 1/2 & 0 \\
0 & 0 & 1 & 0 & 0 & -146/89 &  | & 9/178 & -69/178 & -41/89 & 13/89 & 1/2 & 0 \\
0 & 0 & 0 & 1 & 0 & 316/89 & | & -145/534 & 153/178 & 176/267 & -71/267 & -1/2 & 0 \\
0 & 0 & 0 & 0 & 1 & -105/89 & | & 29/267 & -5/89 & 17/267 & 25/267 & 0 & 0  \\
0 & 0 & 0 & 0 & 0 & 36/89 & | & -313/267 & 78/89 & 73/267 & -34/267 & 0 & 1 \
\end{bmatrix}
$$

12. [R6 = (89/36) R6]

$$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & -369/89 & | & 77/178 & -175/178 & -64/89 & 42/89 & 1/2 & 0 \\
0 & 1 & 0 & 0 & 0 & -147/89 & | & 79/534 & -103/178 & -83/267 & 35/267 & 1/2 & 0 \\
0 & 0 & 1 & 0 & 0 & -146/89 &  | & 9/178 & -69/178 & -41/89 & 13/89 & 1/2 & 0 \\
0 & 0 & 0 & 1 & 0 & 316/89 & | & -145/534 & 153/178 & 176/267 & -71/267 & -1/2 & 0 \\
0 & 0 & 0 & 0 & 1 & -105/89 & | & 29/267 & -5/89 & 17/267 & 25/267 & 0 & 0  \\
0 & 0 & 0 & 0 & 0 & 1 & | & -313/108 & 13/6 & 73/108 & -17/54 & 0 & 89/36 \
\end{bmatrix}
$$

13. [R1 = R1 - ((-369/89) R6)]

    [R2 = R2 - ((-147/89) R6)]

    [R3 = R3 - ((-146/89) R6)]

    [R4 = R4 - ((316/89) R6)]
    
    [R5 = R5 - ((-105/89) R6)]
    
$$
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 0 & | & -139/12 & 8 & 25/12 & -5/6 & 1/2 & 41/4 \\
0 & 1 & 0 & 0 & 0 & 0 & | & -167/36 & 3 & 29/36 & -7/18 & 1/2 & 49/12 \\
0 & 0 & 1 & 0 & 0 & 0 &  | & -127/27 & 19/6 & 35/54 & -10/27 & 1/2 & 73/18 \\
0 & 0 & 0 & 1 & 0 & 0 & | & 541/54 & -41/6 & -47/27 & 23/27 & -1/2 & -79/9 \\
0 & 0 & 0 & 0 & 1 & 0 & | & -127/36 & 5/2 & 31/36 & -5/18 & 0 & 35/12  \\
0 & 0 & 0 & 0 & 0 & 1 & | & -313/108 & 13/6 & 73/108 & -17/54 & 0 & 89/36 \
\end{bmatrix}
$$

BERIKUUT PENYELESAIAN DENGAN MENGGUNAKAN CODE:

In [ ]:
import numpy as np
import sys

# Koefisien matriks 6x6 (ganti dengan koefisien matriks yang sesuai)
a = np.array([[3,2,-1,4,-5,6],[2,-1,3,4,-2,5],[1,4,-2,3,1,2],[4,-1,2,5,3,-4],[1,3,2,4,-1,3],[2,2,-3,1,-4,2]])

# Augmentasi dengan matriks identitas 6x6
n = a.shape[0]
identity_matrix = np.identity(n)
augmented_matrix = np.hstack((a, identity_matrix))

# Terapkan Eliminasi Gauss-Jordan
for i in range(n):
    if augmented_matrix[i][i] == 0.0:
        sys.exit('Pembagian dengan nol terdeteksi!')
    for j in range(n):
        if i != j:
            ratio = augmented_matrix[j][i] / augmented_matrix[i][i]
            for k in range(2 * n):
                augmented_matrix[j][k] = augmented_matrix[j][k] - ratio * augmented_matrix[i][k]

# Operasi baris untuk membuat elemen diagonal utama menjadi 1
for i in range(n):
    divisor = augmented_matrix[i][i]
    for j in range(2 * n):
        augmented_matrix[i][j] = augmented_matrix[i][j] / divisor

# Matriks invers
inverse_matrix = augmented_matrix[:, n:]

# Tampilkan matriks invers
print('\nMATRIKS INVERS ADALAH:')
for i in range(n):
    for j in range(n):
        print(inverse_matrix[i][j], end='\t')
    print()


MATRIKS INVERS ADALAH:
-7.561728395061753	4.777777777777794	0.9691358024691402	-0.3395061728395081	0.5000000000000007	6.592592592592613	
0.2142857142857143	-0.5357142857142858	-0.4285714285714286	-0.0	0.5	-0.0	
6.771851851851871	-5.133333333333346	-2.2140740740740776	0.5651851851851867	0.4999999999999996	-5.537777777777794	
11.342592592592629	-7.791666666666691	-1.9537037037037104	1.0092592592592622	-0.5000000000000007	-9.88888888888892	
-3.527777777777789	2.5000000000000075	0.8611111111111132	-0.2777777777777786	2.0045693500176507e-16	2.9166666666666763	
-2.898148148148157	2.1666666666666727	0.6759259259259276	-0.3148148148148155	1.3466594094990377e-16	2.47222222222223	
