#Tugas 3
## Matriks invers

Matriks yang jika dikalikan dengan matriks asalnya, akan menghasilkan metriks identitas.
Dan sering digunakan dalam pemecahan sistem persamaan linier.

AA^-1 = A^-1 x A = I

I adalah matriks identitas yang memiliki elemen-elemen diagonal bernilai 1 dan elemen-elemen lainnya bernilai 0. Matriks invers ini hanya ada untuk matriks persegi yang tidak singular, determinannya tidak nol. Contoh :

- Matriks dengan ordo(2 x2):

$$
\begin{equation*}
A=
\begin{bmatrix}
a&b\\
c&d
\end{bmatrix}
\end{equation*}
$$
$$
\begin{align*}
A^-1\ =\frac{1}{ad-bc}
\begin{bmatrix}
d&-b\\
-c&a
\end{bmatrix}
\end{align*}
$$

- Matriks dengan ordo (3 x3):

$$
\begin{equation*}
A=
\begin{bmatrix}
a&b&c\\
d&e&f\\
g&h&i\
\end{bmatrix}
\end{equation*}
$$
$$
\begin{equation*}
A^-1=\frac{1}{aei + bfg + cdh - gec - hfa - idb}
Adj A
\end{equation*}
$$


In [ ]:
import numpy as np

a=np.array([[2,-1],[-3,2]])
print('Matriks A =\n', a)

Matriks A =
 [[ 2 -1]
 [-3  2]]


Contoh matriks dengan ordo (2 x2):

$$
\begin{equation*}
A=
\begin{bmatrix}
2&-1\\
-3&2
\end{bmatrix}
\end{equation*}
$$

Untuk mencari inversnya dapat dilakukan dengan mencari determinannya terlebih dahulu, menggunakan rumus di bawah ini.

det A = ad - bc

Berikut penyelesaian determinannya:

det A = (2 x 2) - (-1 x (-3)) = 4 - 3 = 1

Setelah ditemukan nilai determinannya, langkah selanjutnya yaitu masukkan nilai determinan pada rumus invers matriks dengan ordo (2 x 2)

$$
\begin{equation*}
A^-1=\frac{1}{det A}
\begin{bmatrix}
d&-b\\
-c&a
\end{bmatrix}
\end{equation*}
$$

Berikut penyelesaian Matriks invers nya:

$$
\begin{equation*}
A^-1=\frac{1}{1}
\begin{bmatrix}
2&1\\
3&2
\end{bmatrix}
=
\begin{bmatrix}
2&1\\
3&2
\end{bmatrix}
\end{equation*}
$$


In [ ]:
#Berikut Codenya:
import numpy as np

a=np.array([[(1/1)*2, (1/1)*1],[(1/1)*3, (1/1)*2]])
print('Matriks A^-1 =\n', a)

Matriks A^-1 =
 [[2. 1.]
 [3. 2.]]


###Sifat-sifat Matriks invers
1. Hanya dimiliki oleh matriks persegi karna memiliki kolom dan baris yanng sama.
2. Hanya ada matriks non-singular. Determinannya tidak sama dengan 0.
3. Unik : Setiap matriks hanya memiliki satu matriks invers
4. Invers dari invers : Jika Z memiliki invers, maka inversnya adalah matriks Z itu sendiri. $\begin{align*}(Z^-1)^-1=Z\end{align*}$
5. Invers dari hasil kali : Jika Y dan Z adalah matriks yang memiliki invers, maka hasil kali AB juga memiliki invers, dan invernya adalah hasil kali invers secara terbalik. $\begin{align*}(YZ)^-1=(Z^-1)Y^-1\end{align*}$
6. Invers dari tranpose : jika Z merupakan matriks persegi yang memiliki invers dari tranposenya adalah tranpose dari inversnya. $\begin{align*}(Z^T)^-1=(Z^-1)^T\end{align*}$
7. Invers dari matriks identitas : Invers dari matriks identitas I adalah I itu sendiri


In [ ]:
import numpy as np

a=np.array([[4,5,4],[2,1,-3],[-1,-2,4]])
i = np.array([[1,0,0],[0,1,0],[0,0,1]])

print('AI=\n',a@i)
print('IA=\n',i@a)
print('A=\n',a)

AI=
 [[ 4  5  4]
 [ 2  1 -3]
 [-1 -2  4]]
IA=
 [[ 4  5  4]
 [ 2  1 -3]
 [-1 -2  4]]
A=
 [[ 4  5  4]
 [ 2  1 -3]
 [-1 -2  4]]


###Mencari Invers Dengan Eliminasi Gauss Jordan Elimination

Langkah-langkah Eliminasi Gauss Jordan adalah

1. Membuat elemen diagonal utama menjadi 1. Hal ini dilakukan uuntuk mempermudah meng-nol-kan elemen yang bukan diagonal utama.
2. Membuat nol di selain diagonal utama. Hal ini dilakukan dengan menggunakan operasi baris seperti
  - Menukarkan posisi baris satu dengan baris yang lain (RowSwap)
  - Mengkalikan baris dengan bilangan selain nol (RowScale)
  - Menambahkan kelipatan baris ke baris yang lain (RowAdd)
3. Mengulangi proses untuk setiap kolom

Berikut contoh matriks A:
$$
\begin{equation*}
A=
\begin{bmatrix}
6&5\\
8&10
\end{bmatrix}
\end{equation*}
$$

Eliminasi Gauss Jordan dilakukan dengan menempatkan matriks A di sebelah kiri dan matriks identitas(I) di sebelah kanan. Kedua matriks ini dipisahkan dengan garis putus-putus. Seperti berikut:

$$
\begin{equation*}
A=
\begin{bmatrix}
6&5& | &1&0 \\
8&10& | &0&1
\end{bmatrix}
\end{equation*}
$$

Berikut penyelesaian menggunakan Eliminasi Gauss Jordan Elimination:

1. Bagilah baris 1 dengan 6 [R1 = (1/6) R1]

$$
\begin{equation*}
A=
\begin{bmatrix}
1&5/6& | &1/6&0 \\
8&10& | &0&1
\end{bmatrix}
\end{equation*}
$$

2. [R2 = R2 - 8R1]

$$
\begin{equation*}
A=
\begin{bmatrix}
1&5/6& | &1/6&0 \\
0&10/3& | &-4/3&1
\end{bmatrix}
\end{equation*}
$$

3. [R2 = (3/10)R2]

$$
\begin{equation*}
A=
\begin{bmatrix}
1&5/6& | &1/6&0 \\
0&1& | &-2/5&3/10
\end{bmatrix}
\end{equation*}
$$

4. [R1 = R1 - (5/6)R2]

$$
\begin{equation*}
A=
\begin{bmatrix}
1&0& | &1/2&-1/4 \\
0&1& | &-2/5&3/10
\end{bmatrix}
\end{equation*}
$$


In [ ]:
import numpy as np

def invers_matriks_2x2(A):
    # Periksa apakah matriks A dapat diinverskan
    if np.linalg.det(A) == 0:
        print("Matriks tidak dapat diinverskan karena determinan = 0.")
        return None

    # Buat matriks identitas berukuran 2x2
    I = np.eye(2)

    # Gabungkan matriks A dan matriks identitas
    aug_matrix = np.hstack((A, I))

    # Lakukan operasi baris elementer untuk mengubah matriks A menjadi matriks identitas
    for i in range(2):
        # Bagi baris ke-i dengan elemen diagonal
        pivot = aug_matrix[i, i]
        aug_matrix[i, :] /= pivot
        # Kurangi baris lain dengan kelipatan baris ke-i
        for j in range(2):
          if j != i:
            factor = aug_matrix[j, i]
            aug_matrix[j, :] -= factor * aug_matrix[i, :]

     # Matriks invers berada di sisi kanan matriks augmentasi
    invers_A = aug_matrix[:, 2:]

    return invers_A

# Contoh penggunaan
A = np.array([[6, 5], [8, 10]])
invers_A = invers_matriks_2x2(A)
print("Matriks A:")
print(A)
print("\nMatriks invers A:")
print(invers_A)


Matriks A:
[[ 6  5]
 [ 8 10]]

Matriks invers A:
[[ 0.5  -0.25]
 [-0.4   0.3 ]]


### Soal Eliminasi Persamaan Linier

(membuat contoh soal persamaan linier 6 variable)

$$
\\2a + b + 3c + d + 2e + 3f = 15\\
a + b + 6c + d + 3e + 4f = 21\\
2a - 2b + 5c + 4d + e + 4f = 19\\
a + 2b + c + 3d + e + f = 12\\
2a + 2b + 6c + 3d + 2e + 4f = 22\\
3a + 2b + 3c + 2d + e + f = 14\\
$$

Matriks augmented dari sistem persamaan ini :

$$
\begin{bmatrix}
2 & 1 & 3 & 1 & 2 & 3 & | & 15\\
1 & 1 & 6 & 1 & 3 & 4 & | & 21\\
2 & -2 & 5 & 4 & 1 & 4 & | & 19\\
1 & 2 & 1 & 3 & 1 & 1 & | & 12\\
2 & 2 & 6 & 3 & 2 & 4 & | & 22\\
3 & 2 & 3 & 2 & 1 & 1 & | & 14\\
\end{bmatrix}
$$

Menulis matriks augemented:

$$
\begin{bmatrix}
2 & 1 & 3 & 1 & 2 & 3 & | & 1 & 0 & 0 & 0 & 0 & 0\\
1 & 1 & 6 & 1 & 3 & 4 & | & 0 & 1 & 0 & 0 & 0 & 0\\
2 & -2 & 5 & 4 & 1 & 4 & | &  0 & 0 & 1 & 0 & 0 & 0\\
1 & 2 & 1 & 3 & 1 & 1 & | & 0 & 0 & 0 & 1 & 0 & 0\\
2 & 2 & 6 & 3 & 2 & 4 & | & 0 & 0 & 0 & 0 & 1 & 0\\
3 & 2 & 3 & 2 & 1 & 1 & | & 0 & 0 & 0 & 0 & 0 & 1
\end{bmatrix}
$$

BERIKUT PENYELESAIAN MENGGUNAKAN GAUSS JORDAN DARI MATRIKS DI ATAS DENGAN CODE:

In [25]:
# Import library numpy and memasukkan persamaan dalam bentuk matrix
import numpy as np
A = np.array([[2,1,3,1,2,3],[1,1,6,1,3,4],[2,-2,5,4,1,4],[1,2,1,3,1,1],[2,2,6,3,2,4],[3,2,3,2,1,1]])
print(f"Matrix A  = \n{A}")
print("\n")

b = np.array([[15], [21], [19], [12], [22], [14]])
print(f"Matrix b =\n{b}")
print("\n")

print("Kita gabungkan setiap kolom Matrix b ke baris Matrix A")
A = np.array([[2,1,3,1,2,3,15],[1,1,6,1,3,4,21],[2,-2,5,4,1,4,19],[1,2,1,3,1,1,12],[2,2,6,3,2,4,22],[3,2,3,2,1,1,14]])
print(f"Matrix A  = \n{A}")
print("\n")

print("Kita juga definisikan Matrix Identitasnya")
B  = np.array([[1,0,0,0,0,0],[0,1,0,0,0,0],[0,0,1,0,0,0],[0,0,0,1,0,0],[0,0,0,0,1,0],[0,0,0,0,0,1]])
print(f"Matrix I = \n{B}")

Matrix A  = 
[[ 2  1  3  1  2  3]
 [ 1  1  6  1  3  4]
 [ 2 -2  5  4  1  4]
 [ 1  2  1  3  1  1]
 [ 2  2  6  3  2  4]
 [ 3  2  3  2  1  1]]


Matrix b =
[[15]
 [21]
 [19]
 [12]
 [22]
 [14]]


Kita gabungkan setiap kolom Matrix b ke baris Matrix A
Matrix A  = 
[[ 2  1  3  1  2  3 15]
 [ 1  1  6  1  3  4 21]
 [ 2 -2  5  4  1  4 19]
 [ 1  2  1  3  1  1 12]
 [ 2  2  6  3  2  4 22]
 [ 3  2  3  2  1  1 14]]


Kita juga definisikan Matrix Identitasnya
Matrix I = 
[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [26]:
def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped. (menukarkan persamaan)
# =============================================================================
    m = A.shape[0]  # m is number of rows in A (jumlah baris A)
    n = A.shape[1]  # n is number of columns in A (jumlah kolom A)

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale. (mengalikan entry baris A dengan skala)
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modified.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale. (menambahkan nilai baris k dikalikan dengan skala)
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B


In [27]:
print("Tukar baris 1 dengan baris 0")
A1 = RowSwap(A,0,1)
print(A1,"\n")
B1 = RowSwap(B,0,1)
print(B1,"\n")

print("Eliminasi kolom pertama")
print("R1 = R1 + (-2)R0")
A2= RowAdd(A1,0,1,-2)
print(A2,"\n")
B2= RowAdd(B1,0,1,-2)
print(B2,"\n")

print("R2 = R2 + (-2)R0")
A3= RowAdd(A2,0,2,-2)
print(A3,"\n")
B3= RowAdd(B2,0,2,-2)
print(B3,"\n")

print("R3 = R3 + (-1)R0")
A4= RowAdd(A3,0,3,-1)
print(A4,"\n")
B4= RowAdd(B3,0,3,-1)
print(B4,"\n")

print("R4 = R4 + (-2)R0")
A5= RowAdd(A4,0,4,-2)
print(A5,"\n")
B5= RowAdd(B4,0,4,-2)
print(B5,"\n")

print("R5 = R5 + (-3)R0")
A6= RowAdd(A5,0,5,-3)
print(A6,"\n")
B6= RowAdd(B5,0,5,-3)
print(B6,"\n")

Tukar baris 1 dengan baris 0
[[ 1.  1.  6.  1.  3.  4. 21.]
 [ 2.  1.  3.  1.  2.  3. 15.]
 [ 2. -2.  5.  4.  1.  4. 19.]
 [ 1.  2.  1.  3.  1.  1. 12.]
 [ 2.  2.  6.  3.  2.  4. 22.]
 [ 3.  2.  3.  2.  1.  1. 14.]] 

[[0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]] 

Eliminasi kolom pertama
R1 = R1 + (-2)R0
[[  1.   1.   6.   1.   3.   4.  21.]
 [  0.  -1.  -9.  -1.  -4.  -5. -27.]
 [  2.  -2.   5.   4.   1.   4.  19.]
 [  1.   2.   1.   3.   1.   1.  12.]
 [  2.   2.   6.   3.   2.   4.  22.]
 [  3.   2.   3.   2.   1.   1.  14.]] 

[[ 0.  1.  0.  0.  0.  0.]
 [ 1. -2.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.]] 

R2 = R2 + (-2)R0
[[  1.   1.   6.   1.   3.   4.  21.]
 [  0.  -1.  -9.  -1.  -4.  -5. -27.]
 [  0.  -4.  -7.   2.  -5.  -4. -23.]
 [  1.   2.   1.   3.   1.   1.  12.]
 [  2.   2.   6.   3.   2.   4.  22.]
 [  3.   

In [28]:
print("R1 = (-1)R1")
A7 = RowScale(A6,1,-1)
print(A7,"\n")
B7 = RowScale(B6,1,-1)
print(B7,"\n")

print("Eliminasi kolom kedua")
print("R0 = R0 + (-1)R1")
A8 = RowAdd(A7,1,0,-1)
print(A8,"\n")
B8 = RowAdd(B7,1,0,-1)
print(B8,"\n")

print("R2 = R2 + (4)R1")
A9 = RowAdd(A8,1,2,4)
print(A9,"\n")
B9 = RowAdd(B8,1,2,4)
print(B9,"\n")

print("R3 = R3 + (-1)R1")
A10 = RowAdd(A9,1,3,-1)
print(A10,"\n")
B10 = RowAdd(B9,1,3,-1)
print(B10,"\n")

print("R5 = R5 + (-1)R1")
A11 = RowAdd(A10,1,5,1)
print(A11,"\n")
B11 = RowAdd(B10,1,5,1)
print(B11,"\n")

R1 = (-1)R1
[[  1.   1.   6.   1.   3.   4.  21.]
 [ -0.   1.   9.   1.   4.   5.  27.]
 [  0.  -4.  -7.   2.  -5.  -4. -23.]
 [  0.   1.  -5.   2.  -2.  -3.  -9.]
 [  0.   0.  -6.   1.  -4.  -4. -20.]
 [  0.  -1. -15.  -1.  -8. -11. -49.]] 

[[ 0.  1.  0.  0.  0.  0.]
 [-1.  2. -0. -0. -0. -0.]
 [ 0. -2.  1.  0.  0.  0.]
 [ 0. -1.  0.  1.  0.  0.]
 [ 0. -2.  0.  0.  1.  0.]
 [ 0. -3.  0.  0.  0.  1.]] 

Eliminasi kolom kedua
R0 = R0 + (-1)R1
[[  1.   0.  -3.   0.  -1.  -1.  -6.]
 [ -0.   1.   9.   1.   4.   5.  27.]
 [  0.  -4.  -7.   2.  -5.  -4. -23.]
 [  0.   1.  -5.   2.  -2.  -3.  -9.]
 [  0.   0.  -6.   1.  -4.  -4. -20.]
 [  0.  -1. -15.  -1.  -8. -11. -49.]] 

[[ 1. -1.  0.  0.  0.  0.]
 [-1.  2. -0. -0. -0. -0.]
 [ 0. -2.  1.  0.  0.  0.]
 [ 0. -1.  0.  1.  0.  0.]
 [ 0. -2.  0.  0.  1.  0.]
 [ 0. -3.  0.  0.  0.  1.]] 

R2 = R2 + (4)R1
[[  1.   0.  -3.   0.  -1.  -1.  -6.]
 [ -0.   1.   9.   1.   4.   5.  27.]
 [  0.   0.  29.   6.  11.  16.  85.]
 [  0.   1.  -5.   2.  -2. 

In [29]:
print("R2 = (1/29)R2")
A12 = RowScale(A11,2,1/29)
print(A12.round(),"\n")
B12 = RowScale(B11,2,1/29)
print(B12.round(),"\n")

print("Eliminasi kolom ketiga")
print("R0 = R0 + (3)R2")
A13 = RowAdd (A12,2,0,3)
print(A13.round(),"\n")
B13 = RowAdd (B12,2,0,3)
print(B13.round(),"\n")

print("R1 = R1 + (-9)R2")
A14 = RowAdd (A13,2,1,-9)
print(A14.round(),"\n")
B14 = RowAdd (B13,2,1,-9)
print(B14.round(),"\n")

print("R3 = R3 + (14)R2")
A15 = RowAdd (A14,2,3,14)
print(A15.round(),"\n")
B15 = RowAdd (B14,2,3,14)
print(B15.round(),"\n")

print("R4 = R4 + (6)R2")
A16 = RowAdd (A15,2,4,6)
print(A16.round(),"\n")
B16 = RowAdd (B15,2,4,6)
print(B16.round(),"\n")

print("R5 = R5 + (6)R2")
A17 = RowAdd (A16,2,5,6)
print(A17.round(),"\n")
B17 = RowAdd (B16,2,5,6)
print(B17.round(),"\n")
print("jika dibulatkan hasilnya seperti di atas, jika tidak dibulatkan hasilnya seperti dibawah \n")
print(A17,"\n")
print(B17,"\n")

[[  1.   0.  -3.   0.  -1.  -1.  -6.]
 [ -0.   1.   9.   1.   4.   5.  27.]
 [  0.   0.   1.   0.   0.   1.   3.]
 [  0.   0. -14.   1.  -6.  -8. -36.]
 [  0.   0.  -6.   1.  -4.  -4. -20.]
 [  0.   0.  -6.   0.  -4.  -6. -22.]] 

[[ 1. -1.  0.  0.  0.  0.]
 [-1.  2. -0. -0. -0. -0.]
 [-0.  0.  0.  0.  0.  0.]
 [ 1. -3.  0.  1.  0.  0.]
 [ 0. -2.  0.  0.  1.  0.]
 [-1. -1.  0.  0.  0.  1.]] 

Eliminasi kolom ketiga
a
[[  1.   0.   0.   1.   0.   1.   3.]
 [ -0.   1.   9.   1.   4.   5.  27.]
 [  0.   0.   1.   0.   0.   1.   3.]
 [  0.   0. -14.   1.  -6.  -8. -36.]
 [  0.   0.  -6.   1.  -4.  -4. -20.]
 [  0.   0.  -6.   0.  -4.  -6. -22.]] 

[[ 1. -0.  0.  0.  0.  0.]
 [-1.  2. -0. -0. -0. -0.]
 [-0.  0.  0.  0.  0.  0.]
 [ 1. -3.  0.  1.  0.  0.]
 [ 0. -2.  0.  0.  1.  0.]
 [-1. -1.  0.  0.  0.  1.]] 

a
[[  1.   0.   0.   1.   0.   1.   3.]
 [ -0.   1.   0.  -1.   1.   0.   1.]
 [  0.   0.   1.   0.   0.   1.   3.]
 [  0.   0. -14.   1.  -6.  -8. -36.]
 [  0.   0.  -6.   1.  -4.  -

In [39]:
print("R3 = (1/3.8965517241379310344)R3")
A18 = RowScale (A17,3,1/3.8965517241379310344	)
print(A18.round(),"\n")
B18 = RowScale (B17,3,1/3.8965517241379310344	)
print(B18.round(),"\n")

print("Eliminasi kolom keempat")
print("R0 = R0 + (-0.62068965517241379309)R3")
A19 = RowAdd (A18,3,0,-0.62068965517241379309)
print(A19.round(),"\n")
B19 = RowAdd (B18,3,0,-0.62068965517241379309)
print(B19.round(),"\n")

print("R1 = R1 + (0.8620689655172413792)R3")
A20 = RowAdd (A19,3,1,0.8620689655172413792)
print(A20.round(),"\n")
B20 = RowAdd (B19,3,1,0.8620689655172413792)
print(B20.round(),"\n")

print("R2 = R2 + (-0.20689655172413793103)R3")
A21 = RowAdd (A20,3,2,-0.20689655172413793103)
print(A21.round(),"\n")
B21 = RowAdd (B20,3,2,-0.20689655172413793103)
print(B21.round(),"\n")

print("R4 = R4 + (-2.2413793103448275861)R3")
A22 = RowAdd (A21,3,4,-2.2413793103448275861)
print(A22.round(),"\n")
B22 = RowAdd (B21,3,4,-2.2413793103448275861)
print(B22.round(),"\n")

print("R5 = R5 + (-1.2413793103448275861)R3")
A23 = RowAdd (A22,3,5,-1.2413793103448275861)
print(A23.round(),"\n")
B23 = RowAdd (B22,3,5,-1.2413793103448275861)
print(B23.round(),"\n")

print("jika dibulatkan hasilnya seperti di atas, jika tidak dibulatkan hasilnya seperti dibawah \n")
print(A23,"\n")
print(B23,"\n")

R3 = (1/3.8965517241379310344)R3
[[ 1.  0.  0.  1.  0.  1.  3.]
 [-0.  1.  0. -1.  1.  0.  1.]
 [ 0.  0.  1.  0.  0.  1.  3.]
 [ 0.  0.  0.  1. -0. -0.  1.]
 [ 0.  0.  0.  2. -2. -1. -2.]
 [ 0.  0.  0.  1. -2. -3. -4.]] 

[[ 1. -0.  0.  0.  0.  0.]
 [ 0.  0. -0. -0. -0. -0.]
 [-0.  0.  0.  0.  0.  0.]
 [-0. -0.  0.  0.  0.  0.]
 [-1. -1.  0.  0.  1.  0.]
 [-2.  0.  0.  0.  0.  1.]] 

Eliminasi kolom keempat
R0 = R0 + (-0.62068965517241379309)R3
[[ 1.  0.  0.  0.  0.  1.  2.]
 [-0.  1.  0. -1.  1.  0.  1.]
 [ 0.  0.  1.  0.  0.  1.  3.]
 [ 0.  0.  0.  1. -0. -0.  1.]
 [ 0.  0.  0.  2. -2. -1. -2.]
 [ 0.  0.  0.  1. -2. -3. -4.]] 

[[ 1. -0.  0. -0.  0.  0.]
 [ 0.  0. -0. -0. -0. -0.]
 [-0.  0.  0.  0.  0.  0.]
 [-0. -0.  0.  0.  0.  0.]
 [-1. -1.  0.  0.  1.  0.]
 [-2.  0.  0.  0.  0.  1.]] 

R1 = R1 + (0.8620689655172413792)R3
[[ 1.  0.  0.  0.  0.  1.  2.]
 [ 0.  1.  0.  0.  0. -0.  2.]
 [ 0.  0.  1.  0.  0.  1.  3.]
 [ 0.  0.  0.  1. -0. -0.  1.]
 [ 0.  0.  0.  2. -2. -1. -2.]
 [ 0. 

In [31]:
print("R4 = (-1/1.3274336283185840708)R4")
A24 = RowScale (A23,4,-1/1.3274336283185840708	)
print(A24.round(),"\n")
B24 = RowScale (B23,4,-1/1.3274336283185840708	)
print(B24.round(),"\n")

print("Eliminasi kolom kelima")
print("R0 = R0 + (-0.24778761061946902647)R4")
A25 = RowAdd (A24,4,0,-0.24778761061946902647)
print(A25.round(),"\n")
B25 = RowAdd (B24,4,0,-0.24778761061946902647)
print(B25.round(),"\n")

print("R1 = R1 + (-0.43362831858407079652)R4")
A26 = RowAdd (A25,4,1,-0.43362831858407079652)
print(A26.round(),"\n")
B26 = RowAdd (B25,4,1,-0.43362831858407079652)
print(B26.round(),"\n")

print("R2 = R2 + (-0.41592920353982300884)R4")
A27 = RowAdd (A26,4,2,-0.41592920353982300884)
print(A27.round(),"\n")
B27 = RowAdd (B26,4,2,-0.41592920353982300884)
print(B27.round(),"\n")

print("R3 = R3 + (0.17699115044247787614)R4")
A28 = RowAdd (A27,4,3,0.17699115044247787614)
print(A28.round(),"\n")
B28 = RowAdd (B27,4,3,0.17699115044247787614)
print(B28.round(),"\n")

print("R5 = R5 + (1.5044247787610619469)R4")
A29 = RowAdd (A28,4,5,1.5044247787610619469)
print(A29.round(),"\n")
B29 = RowAdd (B28,4,5,1.5044247787610619469)
print(B29.round(),"\n")

print("jika dibulatkan hasilnya seperti di atas, jika tidak dibulatkan hasilnya seperti dibawah \n")
print(A29,"\n")
print(B29,"\n")

a
[[ 1.  0.  0.  0.  0.  1.  2.]
 [ 0.  1.  0.  0.  0. -0.  2.]
 [ 0.  0.  1.  0.  0.  1.  3.]
 [ 0.  0.  0.  1. -0. -0.  1.]
 [-0. -0. -0. -0.  1.  0.  4.]
 [ 0.  0.  0.  0. -2. -3. -6.]] 

[[ 1. -0.  0. -0.  0.  0.]
 [ 0.  0. -0.  0.  0.  0.]
 [-0.  0.  0. -0.  0.  0.]
 [-0. -0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0. -1. -0.]
 [-2.  0.  0. -0.  0.  1.]] 

Eliminasi kolom kelima
a
[[ 1.  0.  0.  0. -0.  1.  1.]
 [ 0.  1.  0.  0.  0. -0.  2.]
 [ 0.  0.  1.  0.  0.  1.  3.]
 [ 0.  0.  0.  1. -0. -0.  1.]
 [-0. -0. -0. -0.  1.  0.  4.]
 [ 0.  0.  0.  0. -2. -3. -6.]] 

[[ 1. -0.  0. -0.  0.  0.]
 [ 0.  0. -0.  0.  0.  0.]
 [-0.  0.  0. -0.  0.  0.]
 [-0. -0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0. -1. -0.]
 [-2.  0.  0. -0.  0.  1.]] 

a
[[ 1.  0.  0.  0. -0.  1.  1.]
 [ 0.  1.  0.  0. -0. -0.  0.]
 [ 0.  0.  1.  0.  0.  1.  3.]
 [ 0.  0.  0.  1. -0. -0.  1.]
 [-0. -0. -0. -0.  1.  0.  4.]
 [ 0.  0.  0.  0. -2. -3. -6.]] 

[[ 1. -0.  0. -0.  0.  0.]
 [-0. -0. -0.  0.  0.  0.]
 [-0.  0.  0. -0.  0

In [40]:
print("R5 = (-1/2)R5")
A30 = RowScale (A29,5,-1/2)
print(A30.round(),"\n")
B30 = RowScale (B29,5,-1/2)
print(B30.round(),"\n")

print("Eliminasi kolom keenam")
print("R0 = R0 + (-0.6)R5")
A31 = RowAdd (A30,5,0,-0.6)
print(A31.round(),"\n")
B31 = RowAdd (B30,5,0,-0.6)
print(B31.round(),"\n")

print("R1 = R1 + (0.2)R5")
A32 = RowAdd (A31,5,1,0.2)
print(A32.round(),"\n")
B32 = RowAdd (B31,5,1,0.2)
print(B32.round(),"\n")

print("R2 = R2 + (-0.4)R5")
A33 = RowAdd (A32,5,2,-0.4)
print(A33.round(),"\n")
B33 = RowAdd (B32,5,2,-0.4)
print(B33.round(),"\n")

print("R4 = R4 + (-0.4)R5")
A34 = RowAdd (A33,5,4,-0.4)
print(A34.round(),"\n")
B34 = RowAdd (B33,5,4,-0.4)
print(B34.round(),"\n")

print("jika dibulatkan hasilnya seperti di atas, jika tidak dibulatkan hasilnya seperti dibawah \n")
print(A34,"\n")
print(B34,"\n")
print("Perhitungan Gauss Jordan telah selesai")

R5 = (-1/2)R5
[[ 1.  0.  0.  0. -0.  1.  1.]
 [ 0.  1.  0.  0. -0. -0.  0.]
 [ 0.  0.  1.  0.  0.  0.  1.]
 [ 0.  0.  0.  1. -0. -0.  2.]
 [-0. -0. -0. -0.  1.  0.  4.]
 [-0. -0. -0. -0.  0.  1. -0.]] 

[[ 1. -0.  0. -0.  0.  0.]
 [-0. -0. -0.  0.  0.  0.]
 [-0. -0. -0. -0.  0.  0.]
 [-0.  0.  0.  0. -0.  0.]
 [ 0.  1.  0.  0. -1. -0.]
 [ 1. -1. -0. -0.  1. -0.]] 

Eliminasi kolom keenam
R0 = R0 + (-0.6)R5
[[ 1.  0.  0.  0. -0.  0.  1.]
 [ 0.  1.  0.  0. -0. -0.  0.]
 [ 0.  0.  1.  0.  0.  0.  1.]
 [ 0.  0.  0.  1. -0. -0.  2.]
 [-0. -0. -0. -0.  1.  0.  4.]
 [-0. -0. -0. -0.  0.  1. -0.]] 

[[ 0. -0.  0. -0. -0.  0.]
 [-0. -0. -0.  0.  0.  0.]
 [-0. -0. -0. -0.  0.  0.]
 [-0.  0.  0.  0. -0.  0.]
 [ 0.  1.  0.  0. -1. -0.]
 [ 1. -1. -0. -0.  1. -0.]] 

R1 = R1 + (0.2)R5
[[ 1.  0.  0.  0. -0.  0.  1.]
 [ 0.  1.  0.  0. -0. -0.  0.]
 [ 0.  0.  1.  0.  0.  0.  1.]
 [ 0.  0.  0.  1. -0. -0.  2.]
 [-0. -0. -0. -0.  1.  0.  4.]
 [-0. -0. -0. -0.  0.  1. -0.]] 

[[ 0. -0.  0. -0. -0.  0.]
 [

In [ ]:
print("Matrix A menjadi Matrix Identitas setelah 34 operasi gaus jordan")
print(f"Matrix A = \n{A34}")
print("\n")
print(f"Matrix A Invers = \n{B34}")
print("\n")
print(f"Pembulatan Matrix A Invers = \n{B34.round()}")

Matrix A menjadi Matrix Identitas setelah 34 operasi gaus jordan
Matrix A = 
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  -1.49880108e-16  1.11022302e-16  1.42666667e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
  -3.33066907e-17 -8.32667268e-17  8.00000000e-02]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00
  -4.44089210e-17  0.00000000e+00  1.10666667e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.38777878e-16 -1.80411242e-16  2.06666667e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   1.00000000e+00 -3.88578059e-16  3.64000000e+00]
 [-0.00000000e+00 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00
   1.11022302e-16  1.00000000e+00  4.66666667e-01]]


Matrix A Invers = 
[[ 3.20000000e-01 -1.73333333e-01  5.33333333e-02 -1.66666667e-01
  -1.53333333e-01  3.00000000e-01]
 [ 6.00000000e-02 -2.20000000e-01 -2.40000000e-01  6.93889390e-18
   4.40000000e-01 -1.00000000e-0

Jadi ketemu:

x1 = 1

x2 = 0

x3 = 1

x4 = 2

x5 = 4

x6 = 0

Lalu kita substitusikan ke persamaan.  

Persamaan awal :

$$
\\2a + b + 3c + d + 2e + 3f = 15\\
a + b + 6c + d + 3e + 4f = 21\\
2a - 2b + 5c + 4d + e + 4f = 19\\
a + 2b + c + 3d + e + f = 12\\
2a + 2b + 6c + 3d + 2e + 4f = 22\\
3a + 2b + 3c + 2d + e + f = 14\\
$$

Persamaan setelah disubsitusi :

$$
\\2(1) + 1(0) + 3(1) + 1(2) + 2(4) + 3(0) = 2 + 0 + 3 + 2 + 8 + 0 = 15\\
1(1) + 1(0) + 6(1) + 1(2) + 3(4) + 4(0) = 1 + 0 + 6 + 2 + 12 + 0 = 21\\
2(1) - 2(0) + 5(1) + 4(2) + 1(4) + 4(0) = 2 + 0 + 5 + 8 + 4 + 0 = 19\\
1(1) + 2(0) + 1(1) + 3(2) + 1(4) + 1(0) = 1 + 0 + 1 + 6 + 4 + 0 = 12\\
2(1) + 2(0) + 6(1) + 3(2) + 2(4) + 4(0) = 2 + 0 + 6 + 6 + 8 + 0 = 22\\
3(1) + 2(0) + 3(1) + 2(2) + 1(4) + 1(0) = 3 + 0 + 3 + 4 + 4 + 0 = 14\\
$$

Dengan hasil diatas menunjukkan bahwa kita bisa menggunakan Operasi Gaus jordan untuk mencari nilai dari setiap variable dan juga bisa mencari invers dari matriks tersebut. Barikut invers dari matriks A :


$$
\begin{equation*}
A^-1=
\begin{bmatrix}
0.32 & -0.173 & 0.053 & -0.167 & -0.153 & 0.3\\
0.06 & -0.22 & -0.24 & 0 & 0.44 & -0.1\\
-0.42 & 0.207 & 0.013 & -0.167 & 0.087 & 0.2\\
-0.2 & 0.067 & 0.133 & 0.333 & -0.133 & 0\\
-0.02 & 0.74 & 0.08 & 0.5 & -0.98 & 0.2\\
0.6 & -0.533 & -0.067 & -0.167 & 0.567 & -0.5\\
\end{bmatrix}
\end{equation*}
$$


Pembuktian :

A (X) = B

maka,

X = $\begin{align*}(A^-1)\end{align*}$ B

In [37]:
b = np.array([[15], [21], [19], [12], [22], [14]])
print("Ax = b")
print(f"Ax = {b}")

print("\n")
print("x = A^-1 b")
coba = B34 @ b
print(f"x = {coba.round()}")

Ax = b
Ax = [[15]
 [21]
 [19]
 [12]
 [22]
 [14]]


x = A^-1 b
x = [[ 1.]
 [ 0.]
 [ 1.]
 [ 2.]
 [ 4.]
 [-0.]]


Pembuktian :

$\begin{align*}A^-1\end{align*}$ x $\begin{align*}A \end{align*}$ = $\begin{align*}I\end{align*}$

In [38]:
C = B34 @ A
print("A_invers x A = I")
print(f"A_invers x A =\n{C.round()}")

A_invers x A = I
A_invers x A =
[[ 1.  0.  0.  0.  0.  0.  1.]
 [ 0.  1.  0. -0.  0.  0.  0.]
 [ 0. -0.  1. -0. -0. -0.  1.]
 [ 0.  0.  0.  1.  0.  0.  2.]
 [ 0.  0. -0.  0.  1.  0.  4.]
 [-0.  0. -0.  0. -0.  1.  0.]]
