##Menggambarkan persamaan bidang dalam 3D

##Persamaan sistem linier
Penyelesaian sistem persamaan linier menggunakan eliminasi gauss

Selesaikan persamaan berikut:
$$
8x_1+9x_2+x_3=19\\
x_1+2x_2+3x_3=9\\
2x_1+x_2+x_3=5
$$

Berikut penyelesaian di atas

In [ ]:
import numpy as np
A=np.array([[8,9,1,19],[1,2,3,9],[2,1,1,5]])
print(A)

[[ 8  9  1 19]
 [ 1  2  3  9]
 [ 2  1  1  5]]


###Mendefinisikan fungsi operasi baris eliminasi GAUSS



*   RowSwap()
    adalah pertukaran (swap) baris dalam sebuah matriks. RowSwap digunakan untuk melakukan operasi pengubahan atau pengolahan data pada matriks.
*   RowScale()
    adalah operasi untuk mengalikan setiap elemen dalam sebuah baris matriks dengan suatu skalar tertentu sehingga dapat melakukan transformasi pada matriks.
*   RowAdd()
    adalah operasi pada matriks, indeks baris A (hasil penambahan akan ditempatkan), indeks baris B (yang akan ditambahkan ke baris A), dan opsional skala (sebagai faktor untuk mengalikan baris B sebelum menambahkannya). Fungsi tersebut kemudian menambahkan baris B (setelah dikalikan dengan skala jika diberikan) ke baris A, menghasilkan matriks baru dengan baris yang telah diubah.





In [ ]:
def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

Tahapan penyelesaian dengan menggunakan eliminasi gauss

In [4]:
A1 = RowSwap(A,0,1)
print(A1,'\n')

A2 = RowAdd(A1,0,1,-8)
print(A2,'\n')

A3 = RowAdd(A2,0,2,-2)
print(A3,'\n')

A4 = RowAdd(A3,1,2,)
print(A4,'\n')


NameError: name 'RowSwap' is not defined