## Aljabar Matriks
#tidak mengerjakan di luar
- Berikan penjelasan tentang apa itu matriks
- Operasi matriks
  - penjumlahan
  - perkalian
  - pengurangan
  - transpose matriks
- Buat program untuk mengalikan matrik A dan B tidak menggunakan '@'

saya disuruh membuat matriks A dan B dengan ordo 3X3 dan matriks C dengan ordo 3X2

#Penjelasan Mengenai Matriks
##Matriks adalah..

#Operasi pada Matriks
contoh matriks sebagai berikut:

In [30]:
import numpy as np
import sympy as sy

a=np.array([[2,3,2],[4,1,-3],[-1,-2,2]])
b=np.array([[2,4,7],[6,-3,2],[5,-2,7]])
c=np.array([[3,4],[-2,4],[2,5]])
print('A=\n',a)
print('B=\n',b)
print('C=\n',c)

A=
 [[ 2  3  2]
 [ 4  1 -3]
 [-1 -2  2]]
B=
 [[ 2  4  7]
 [ 6 -3  2]
 [ 5 -2  7]]
C=
 [[ 3  4]
 [-2  4]
 [ 2  5]]


##1.Penjumlahan matriks :



  Note!!
  
  penjumlahan dan pengurangan matriks yaitu matriks yang akan dijumlahkan atau dikurangkan harus memiliki ordo atau ukuran yang sama. Artinya, jumlah baris dan kolomnya harus sama.

In [37]:
print('A+B=\n',a+b)
print('B+A=\n',b+a)
print('Sifat di atas merupakan sifat komutatif karena A+B = B+A')

A+B=
 [[ 4  7  9]
 [10 -2 -1]
 [ 4 -4  9]]
B+A=
 [[ 4  7  9]
 [10 -2 -1]
 [ 4 -4  9]]
Sifat di atas merupakan sifat komutatif karena A+B = B+A


##2.Pengurangan Matriks:

In [38]:
print('A-B=\n',a-b)
print('B-A=\n',b-a)
print('Sifat di atas merupakan sifat komutatif karena A-B = B-A')

A-B=
 [[ 0 -1 -5]
 [-2  4 -5]
 [-6  0 -5]]
B-A=
 [[ 0  1  5]
 [ 2 -4  5]
 [ 6  0  5]]
Sifat di atas merupakan sifat komutatif karena A-B = B-A


##3.Perkalian Matriks:

Note!!

Untuk melakukan perkalian matriks A dan B, jumlah kolom dalam matriks A harus sama dengan jumlah baris dalam matriks B. Contoh matriks A memiliki ordo atau ukuran mxn, maka matriks B harus memiliki ordo atau ukuran nxp. Sehingga hasil dari perkalian tersebut akan menghasilkan matriks baru dengan ukuran mxp. Hasilnya akan memiliki jumlah baris yang sama dengan matriks A dan jumlah kolom yang sama dengan matriks B.

In [46]:
print('AB=\n',a@b)
print('AC=\n',a@c)
print('BC=\n',b@c)

AB=
 [[32 -5 34]
 [-1 19  9]
 [-4 -2  3]]
AC=
 [[ 4 30]
 [ 4  5]
 [ 5 -2]]
BC=
 [[12 59]
 [28 22]
 [33 47]]


- Sifat Asosiasi:

  (AB)C = A(BC)

In [42]:
print('A(BC)\n',a@(b@c))
print('(AB)C =\n',(a@b)@c)

Sifat Asosiasi: (AB)C = A(BC)
A(BC)
 [[174 278]
 [-23 117]
 [ -2  -9]]
(AB)C =
 [[174 278]
 [-23 117]
 [ -2  -9]]


- Perkalian skalar:

  c(AB) = (cA)B = A(cB)

In [ ]:
c = 3
print('c(AB)\n',c*(a@b))
print('(cA)B\n',(c*a)@b)
print('A(cB)\n',a@(c*b))

- Perkalian identitas:

  AI = IA = A

In [43]:
i = np.array([[1,0,0],[0,1,0],[0,0,1]])
print('AI=\n',a@i)
print('IA=\n',i@a)
print('A=\n',a)

AI=
 [[ 2  3  2]
 [ 4  1 -3]
 [-1 -2  2]]
IA=
 [[ 2  3  2]
 [ 4  1 -3]
 [-1 -2  2]]
A=
 [[ 2  3  2]
 [ 4  1 -3]
 [-1 -2  2]]


- Perkalian nol:

  A0 = 0A = A

In [ ]:
print('A0=\n',a*0)
print('0A=\n',0*a)
print('A=\n',a)

- Tidak berlaku sifat kumutatif:

  AB != BA atau AB tidak sama dengan BA

In [ ]:
print('AB=\n',a@b)
print('BA=\n',b@a)

##4.Transpose Matriks

In [45]:
c_tran = c.transpose()
print('matrik c sebelum di transpose=\n', c)
print('matrik c setelah di transpose=\n',c_tran)
print('ordo C_transpose adalah',c_tran.shape)
z=c_tran@c
print('Z = C_transpose x C =\n',z)
print('ordo z adalah',z.shape)
p=c@c_tran
print('P = C_transpose x C =\n',p)
print('ordo P adalah',p.shape)

matrik c sebelum di transpose=
 [[ 3  4]
 [-2  4]
 [ 2  5]]
matrik c setelah di transpose=
 [[ 3 -2  2]
 [ 4  4  5]]
ordo C_transpose adalah (2, 3)
Z = C_transpose x C =
 [[17 14]
 [14 57]]
ordo z adalah (2, 2)
P = C_transpose x C =
 [[25 10 26]
 [10 20 16]
 [26 16 29]]
ordo P adalah (3, 3)


#Program untuk Mengalikan Matriks

In [48]:
s=int(input("Masukkan numerik matriks 1 baris 1: "))
ss=int(input("Masukkan numerik matriks 1 baris 2: "))
sss=int(input("Masukkan numerik matriks 1 baris 3: "))
r=int(input("Masukkan numerik matriks 2 baris 1: "))
rr=int(input("Masukkan numerik matriks 2 baris 2: "))
rrr=int(input("Masukkan numerik matriks 2 baris 3: "))

x = int(input("Masukkan jumlah kolom matriks X:"))
y = int(input("Masukkan jumlah baris matriks Y:"))
if x != y:
  print("Perkalian pada matriks X dan Y tidak bisa dilakukan karena jumlah kolom dan barisnya berbeda")



Masukkan numerik matriks 1 baris 1: 2,-3,5


ValueError: invalid literal for int() with base 10: '2,-3,5'